In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urljoin
from numpy import dtype
import re
import json
from pathlib import Path

In [3]:
BASE_URL = "https://mktickets.mk"

response = requests.get(BASE_URL)

response.status_code

200

In [4]:
html = response.text
html[522:579]

'<title>MKTickets - Buy Online Tickets : MKTickets</title>'

In [5]:
soup = BeautifulSoup(html, "html.parser")
soup.title

In [6]:
all_cards = soup.find_all("div")

len(all_cards)

281

In [7]:
all_cards[10].prettify()

'<div class="col-md-6 col-sm-12 col-xs-12 home-top-first home-top-col">\n <div class="slider-wrapper">\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/lord-of-the-dance/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" fetchpriority="high" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg" srcset="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg 640w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-250x164.jpg 250w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-120x79.jpg 120w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-2x1.jpg 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/lord-of-the-dance/">\n      LORD OF THE DANCE\n     </a>\n    </h3>\n    <p>\n     <span>\n      Спортски центар „Јане Сандански”, Скопје,\n     </span>\n     <span>\n      07-04-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png" srcset="https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png 640w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/">\n      ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“\n     </a>\n    </h3>\n    <p>\n     <span>\n      Спортски центар „Јане Сандански”, Скопје,\n     </span>\n     <span>\n      09-04-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/the-young-gods/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png" srcset="https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png 640w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/the-young-gods/">\n      THE YOUNG GODS\n     </a>\n    </h3>\n    <p>\n     <span>\n      Младински Културен Центар, Скопје,\n     </span>\n     <span>\n      14-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2026/01/640x4202.png" srcset="https://mktickets.mk/wp-content/uploads/2026/01/640x4202.png 640w, https://mktickets.mk/wp-content/uploads/2026/01/640x4202-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2026/01/640x4202-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2026/01/640x4202-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/">\n      Јован Јованов, Елвир Мекиќ и пријателите\n     </a>\n    </h3>\n    <p>\n     <span>\n      С.Ц. Борис Трајковски, Скопје,\n     </span>\n     <span>\n      06-06-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/joce-panov/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/12/jp.png" srcset="https://mktickets.mk/wp-content/uploads/2025/12/jp.png 640w, https://mktickets.mk/wp-content/uploads/2025/12/jp-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/12/jp-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/12/jp-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/joce-panov/">\n      ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2\n     </a>\n    </h3>\n    <p>\n     <span>\n      Македонска Филхармонија, Скопје,\n     </span>\n     <span>\n      18-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/lord-of-the-dance/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg" srcset="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg 640w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-250x164.jpg 250w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-120x79.jpg 120w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-2x1.jpg 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/lord-of-the-dance/">\n      LORD OF THE DANCE\n     </a>\n    </h3>\n    <p>\n     <span>\n      Спортски центар „Јане Сандански”, Скопје,\n     </span>\n     <span>\n      07-04-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png" srcset="https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png 640w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/">\n      ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“\n     </a>\n    </h3>\n    <p>\n     <span>\n      Спортски центар „Јане Сандански”, Скопје,\n     </span>\n     <span>\n      09-04-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/the-young-gods/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png" srcset="https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png 640w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/the-young-gods/">\n      THE YOUNG GODS\n     </a>\n    </h3>\n    <p>\n     <span>\n      Младински Културен Центар, Скопје,\n     </span>\n     <span>\n      14-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2026/01/640x4202.png" srcset="https://mktickets.mk/wp-content/uploads/2026/01/640x4202.png 640w, https://mktickets.mk/wp-content/uploads/2026/01/640x4202-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2026/01/640x4202-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2026/01/640x4202-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/">\n      Јован Јованов, Елвир Мекиќ и пријателите\n     </a>\n    </h3>\n    <p>\n     <span>\n      С.Ц. Борис Трајковски, Скопје,\n     </span>\n     <span>\n      06-06-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/joce-panov/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/12/jp.png" srcset="https://mktickets.mk/wp-content/uploads/2025/12/jp.png 640w, https://mktickets.mk/wp-content/uploads/2025/12/jp-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/12/jp-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/12/jp-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/joce-panov/">\n      ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2\n     </a>\n    </h3>\n    <p>\n     <span>\n      Македонска Филхармонија, Скопје,\n     </span>\n     <span>\n      18-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/lord-of-the-dance/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg" srcset="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg 640w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-250x164.jpg 250w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-120x79.jpg 120w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-2x1.jpg 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/lord-of-the-dance/">\n      LORD OF THE DANCE\n     </a>\n    </h3>\n    <p>\n     <span>\n      Спортски центар „Јане Сандански”, Скопје,\n     </span>\n     <span>\n      07-04-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png" srcset="https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png 640w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/">\n      ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“\n     </a>\n    </h3>\n    <p>\n     <span>\n      Спортски центар „Јане Сандански”, Скопје,\n     </span>\n     <span>\n      09-04-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/the-young-gods/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png" srcset="https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png 640w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/the-young-gods/">\n      THE YOUNG GODS\n     </a>\n    </h3>\n    <p>\n     <span>\n      Младински Културен Центар, Скопје,\n     </span>\n     <span>\n      14-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2026/01/640x4202.png" srcset="https://mktickets.mk/wp-content/uploads/2026/01/640x4202.png 640w, https://mktickets.mk/wp-content/uploads/2026/01/640x4202-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2026/01/640x4202-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2026/01/640x4202-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/">\n      Јован Јованов, Елвир Мекиќ и пријателите\n     </a>\n    </h3>\n    <p>\n     <span>\n      С.Ц. Борис Трајковски, Скопје,\n     </span>\n     <span>\n      06-06-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/joce-panov/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/12/jp.png" srcset="https://mktickets.mk/wp-content/uploads/2025/12/jp.png 640w, https://mktickets.mk/wp-content/uploads/2025/12/jp-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/12/jp-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/12/jp-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/joce-panov/">\n      ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2\n     </a>\n    </h3>\n    <p>\n     <span>\n      Македонска Филхармонија, Скопје,\n     </span>\n     <span>\n      18-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/lord-of-the-dance/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg" srcset="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg 640w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-250x164.jpg 250w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-120x79.jpg 120w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-2x1.jpg 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/lord-of-the-dance/">\n      LORD OF THE DANCE\n     </a>\n    </h3>\n    <p>\n     <span>\n      Спортски центар „Јане Сандански”, Скопје,\n     </span>\n     <span>\n      07-04-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png" srcset="https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png 640w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/">\n      ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“\n     </a>\n    </h3>\n    <p>\n     <span>\n      Спортски центар „Јане Сандански”, Скопје,\n     </span>\n     <span>\n      09-04-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/the-young-gods/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png" srcset="https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png 640w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/the-young-gods/">\n      THE YOUNG GODS\n     </a>\n    </h3>\n    <p>\n     <span>\n      Младински Културен Центар, Скопје,\n     </span>\n     <span>\n      14-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2026/01/640x4202.png" srcset="https://mktickets.mk/wp-content/uploads/2026/01/640x4202.png 640w, https://mktickets.mk/wp-content/uploads/2026/01/640x4202-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2026/01/640x4202-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2026/01/640x4202-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/">\n      Јован Јованов, Елвир Мекиќ и пријателите\n     </a>\n    </h3>\n    <p>\n     <span>\n      С.Ц. Борис Трајковски, Скопје,\n     </span>\n     <span>\n      06-06-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/joce-panov/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/12/jp.png" srcset="https://mktickets.mk/wp-content/uploads/2025/12/jp.png 640w, https://mktickets.mk/wp-content/uploads/2025/12/jp-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/12/jp-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/12/jp-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/joce-panov/">\n      ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2\n     </a>\n    </h3>\n    <p>\n     <span>\n      Македонска Филхармонија, Скопје,\n     </span>\n     <span>\n      18-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/lord-of-the-dance/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg" srcset="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg 640w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-250x164.jpg 250w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-120x79.jpg 120w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-2x1.jpg 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/lord-of-the-dance/">\n      LORD OF THE DANCE\n     </a>\n    </h3>\n    <p>\n     <span>\n      Спортски центар „Јане Сандански”, Скопје,\n     </span>\n     <span>\

In [8]:
events_titles = []

for card in all_cards[:]:
    title_tag = card.select_one("div.event-hover > h3")

    if not title_tag:
        continue

    event = {
        "title": title_tag.text.strip()
    }

    events_titles.append(event)

events_titles

[{'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите'},
 {'title': 'ТЕАТАР ЗА ДЕЦА И МЛАДИНЦИ – Месечен репертоар'},
 {'title': 'ТЕАТАР ЗА ДЕЦА И МЛАДИНЦИ – Месечен репертоар'},
 {'title': 'ТЕАТАР ЗА ДЕЦА И МЛАДИНЦИ – Месечен репертоар'},
 {'title': 'ТЕАТАР ЗА ДЕЦА И МЛАДИНЦИ – Месечен репертоар'},
 {'title': 'ТЕАТАР ЗА ДЕЦА И МЛАДИНЦИ – Месечен репертоар'},
 {'title': 'ТЕАТАР ЗА ДЕЦА И МЛАДИНЦИ – Месечен репертоар'},
 {'title': 'ДРАМСКИ ТЕАТАР – МЕСЕЧЕН РЕПЕРТОАР'},
 {'title': 'ДРАМСКИ ТЕАТАР – МЕСЕЧЕН РЕПЕРТОАР'},
 {'title': 'ДРАМСКИ ТЕАТАР – МЕСЕЧЕН РЕПЕРТОАР'},
 {'title': 'Златна Бубамара на Популарноста #29'},
 {'title': 'Златна Бубамара на Популарноста #29'},
 {'title': 'Златна Бубамара на Популарноста #29'},
 {'title': 'СИТЕ НАЈУБАВИ НЕШТА 27.02.2026'},
 {'title': 'СИТЕ НАЈУБАВИ НЕШТА 27.02.2026'},
 {'title': 'СИТЕ НАЈУБАВИ НЕШТА 27.02.2026'},
 {'title': 'Македонија – Луксембург  Претквалификации за Евробаскет 2029'},
 {'title': 'Македонија – Луксембург  Претквалификации за Евробаскет 2029'},
 {'title': 'Македонија – Луксембург  Претквалификации за Евробаскет 2029'},
 {'title': 'FRED WESLEY TRIO'},
 {'title': 'FRED WESLEY TRIO'},
 {'title': 'FRED WESLEY TRIO'},
 {'title': 'Сонуваме Менуваме'},
 {'title': 'Сонуваме Менуваме'},
 {'title': 'Сонуваме Менуваме'},
 {'title': 'Ivan Bosiljčić i Jelena Tomašević 07.03.2026'},
 {'title': 'Ivan Bosiljčić i Jelena Tomašević 07.03.2026'},
 {'title': 'Ivan Bosiljčić i Jelena Tomašević 07.03.2026'},
 {'title': 'МЕТАЛКОВЦИ – ПАТУВААТ!'},
 {'title': 'МЕТАЛКОВЦИ – ПАТУВААТ!'},
 {'title': 'МЕТАЛКОВЦИ – ПАТУВААТ!'},
 {'title': 'Ivan Bosiljčić i Jelena Tomašević'},
 {'title': 'Ivan Bosiljčić i Jelena Tomašević'},
 {'title': 'Ivan Bosiljčić i Jelena Tomašević'},
 {'title': 'Jelena Tomasevic & Ivan Bosiljčić Битола'},
 {'title': 'Jelena Tomasevic & Ivan Bosiljčić Битола'},
 {'title': 'Jelena Tomasevic & Ivan Bosiljčić Битола'},
 {'title': 'Jelena Tomasevic & Ivan Bosiljčić Битола 10.03.2026'},
 {'title': 'Jelena Tomasevic & Ivan Bosiljčić Битола 10.03.2026'},
 {'title': 'Jelena Tomasevic & Ivan Bosiljčić Битола 10.03.2026'},
 {'title': 'ТИХОМИР ПОП АСАНОВИЌ'},
 {'title': 'ТИХОМИР ПОП АСАНОВИЌ'},
 {'title': 'ТИХОМИР ПОП АСАНОВИЌ'},
 {'title': 'СИТЕ НАЈУБАВИ НЕШТА 13.03.2026'},
 {'title': 'СИТЕ НАЈУБАВИ НЕШТА 13.03.2026'},
 {'title': 'СИТЕ НАЈУБАВИ НЕШТА 13.03.2026'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'Artist Republic – Регионална конвенција за тетовирање'},
 {'title': 'Artist Republic – Регионална конвенција за тетовирање'},
 {'title': 'Artist Republic – Регионална конвенција за тетовирање'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'НАЦИОНАЛЕН ЏЕЗ ОРКЕСТАР СО MIKE HOLOBER'},
 {'title': 'НАЦИОНАЛЕН ЏЕЗ ОРКЕСТАР СО MIKE HOLOBER'},
 {'title': 'НАЦИОНАЛЕН ЏЕЗ ОРКЕСТАР СО MIKE HOLOBER'},
 {'title': 'Глумците Пеат 24.03'},
 {'title': 'Глумците Пеат 24.03'},
 {'title': 'Глумците Пеат 24.03'},
 {'title': 'Глумците Пеат 25.03'},
 {'title': 'Глумците Пеат 25.03'},
 {'title': 'Глумците Пеат 25.03'},
 {'title': '„Миланова игра“ – концерт во чест на Милан Завков'},
 {'title': '„Миланова игра“ – концерт во чест на Милан Завков'},
 {'title': '„Миланова игра“ – концерт во чест на Милан Завков'},
 {'title': 'STEFANI & THE UPPER ROOM'},
 {'title': 'STEFANI & THE UPPER ROOM'},
 {'title': 'STEFANI & THE UPPER ROOM'},
 {'title': 'Љубојна – 25 години'},
 {'title': 'Љубојна – 25 години'},
 {'title': 'Љубојна – 25 години'},
 {'title': 'Beauty Expo ’26'},
 {'title': 'Beauty Expo ’26'},
 {'title': 'Beauty Expo ’26'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'Горан Винчиќ Винча – Комедијата е сериозна работа'},
 {'title': 'Горан Винчиќ Винча – Комедијата е сериозна работа'},
 {'title': 'Горан Винчиќ Винча – Комедијата е сериозна работа'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите'},
 {'title': 'Д фестивал 2026'},
 {'title': 'Д фестивал 2026'},
 {'title': 'Д фестивал 2026'},
 {'title': 'AUTECHRE'},
 {'title': 'AUTECHRE'},
 {'title': 'AUTECHRE'},
 {'title': 'Ezhel Live in Europe 2026'},
 {'title': 'Ezhel Live in Europe 2026'},
 {'title': 'Ezhel Live in Europe 2026'}]

In [9]:
len(events_titles)

161

In [10]:
df_events_titles = pd.DataFrame(data=events_titles)

df_events_titles

                         title
0            LORD OF THE DANCE
1            LORD OF THE DANCE
2            LORD OF THE DANCE
3            LORD OF THE DANCE
4            LORD OF THE DANCE
..                         ...
156                   AUTECHRE
157                   AUTECHRE
158  Ezhel Live in Europe 2026
159  Ezhel Live in Europe 2026
160  Ezhel Live in Europe 2026

[161 rows x 1 columns]

In [11]:
unique_events_titles = df_events_titles["title"].unique()

unique_events_titles

array(['LORD OF THE DANCE', 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“',
       'THE YOUNG GODS', 'Јован Јованов, Елвир Мекиќ и пријателите',
       'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2',
       'ТЕАТАР ЗА ДЕЦА И МЛАДИНЦИ – Месечен репертоар',
       'ДРАМСКИ ТЕАТАР – МЕСЕЧЕН РЕПЕРТОАР',
       'Златна Бубамара на Популарноста #29',
       'СИТЕ НАЈУБАВИ НЕШТА 27.02.2026',
       'Македонија – Луксембург  Претквалификации за Евробаскет 2029',
       'FRED WESLEY TRIO', 'Сонуваме Менуваме',
       'Ivan Bosiljčić i Jelena Tomašević 07.03.2026',
       'МЕТАЛКОВЦИ – ПАТУВААТ!', 'Ivan Bosiljčić i Jelena Tomašević',
       'Jelena Tomasevic & Ivan Bosiljčić Битола',
       'Jelena Tomasevic & Ivan Bosiljčić Битола 10.03.2026',
       'ТИХОМИР ПОП АСАНОВИЌ', 'СИТЕ НАЈУБАВИ НЕШТА 13.03.2026',
       'Artist Republic – Регионална конвенција за тетовирање',
       'НАЦИОНАЛЕН ЏЕЗ ОРКЕСТАР СО MIKE HOLOBER', 'Глумците Пеат 24.03',
       'Глумците Пеат 25.03',
       '„Миланова игра“ – концерт во чест на Милан Завков',
       'STEFANI & THE UPPER ROOM', 'Љубојна – 25 години',
       'Beauty Expo ’26',
       'Горан Винчиќ Винча – Комедијата е сериозна работа',
       'Д фестивал 2026', 'AUTECHRE', 'Ezhel Live in Europe 2026'],
      dtype=object)

In [12]:
len(unique_events_titles)

31

In [13]:
detail_links = []

for card in all_cards:
    a = card.select_one("a.poster-link")
    if a and a.get("href"):

        detail_links.append(a["href"])

detail_links

['https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
 'https://mktickets.mk/event/the-young-gods/',
 'https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
 'https://mktickets.mk/event/the-young-gods/',
 'https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
 'https://mktickets.mk/event/the-young-gods/',
 'https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
 'https://mktickets.mk/event/the-young-gods/',
 'https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
 'https://mktickets.mk/event/the-young-gods/',
 'https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
 'https://mktickets.mk/event/the-young-gods/',
 'https://mktickets.mk/event/the-young-gods/',
 'https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/',
 'https://mktickets.mk/event/tdm/',
 'https://mktickets.mk/event/tdm/',
 'https://mktickets.mk/event/tdm/',
 'https://mktickets.mk/event/tdm/',
 'https://mktickets.mk/event/tdm/',
 'https://mktickets.mk/event/dramskiteatar-2/',
 'https://mktickets.mk/event/dramskiteatar-2/',
 'https://mktickets.mk/event/zbm29/',
 'https://mktickets.mk/event/zbm29/',
 'https://mktickets.mk/event/snn27022026/',
 'https://mktickets.mk/event/snn27022026/',
 'https://mktickets.mk/event/makedonija-luxemburg/',
 'https://mktickets.mk/event/makedonija-luxemburg/',
 'https://mktickets.mk/event/fred-wesley-trio/',
 'https://mktickets.mk/event/fred-wesley-trio/',
 'https://mktickets.mk/event/sonuvame/',
 'https://mktickets.mk/event/sonuvame/',
 'https://mktickets.mk/event/ivan-bosiljcic-i-jelena-tomasevic-07-03-2026/',
 'https://mktickets.mk/event/ivan-bosiljcic-i-jelena-tomasevic-07-03-2026/',
 'https://mktickets.mk/event/metalkovci/',
 'https://mktickets.mk/event/metalkovci/',
 'https://mktickets.mk/event/ibjt/',
 'https://mktickets.mk/event/ibjt/',
 'https://mktickets.mk/event/jelena-tomasevic-ivan-bosiljcic-bitola/',
 'https://mktickets.mk/event/jelena-tomasevic-ivan-bosiljcic-bitola/',
 'https://mktickets.mk/event/jelena-tomasevic-ivan-bosiljcic-bt-10032026/',
 'https://mktickets.mk/event/jelena-tomasevic-ivan-bosiljcic-bt-10032026/',
 'https://mktickets.mk/event/tihomir-pop-asanovikj/',
 'https://mktickets.mk/event/tihomir-pop-asanovikj/',
 'https://mktickets.mk/event/snn13032026/',
 'https://mktickets.mk/event/snn13032026/',
 'https://mktickets.mk/event/the-young-gods/',
 'https://mktickets.mk/event/the-young-gods/',
 'https://mktickets.mk/event/ar/',
 'https://mktickets.mk/event/ar/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/njo-mike-holober/',
 'https://mktickets.mk/event/njo-mike-holober/',
 'https://mktickets.mk/event/glumcite-peat-2403/',
 'https://mktickets.mk/event/glumcite-peat-2403/',
 'https://mktickets.mk/event/glumcite-peat-2503/',
 'https://mktickets.mk/event/glumcite-peat-2503/',
 'https://mktickets.mk/event/milanova-igra/',
 'https://mktickets.mk/event/milanova-igra/',
 'https://mktickets.mk/event/stefani-the-upper-room/',
 'https://mktickets.mk/event/stefani-the-upper-room/',
 'https://mktickets.mk/event/ljubojna-25-godini/',
 'https://mktickets.mk/event/ljubojna-25-godini/',
 'https://mktickets.mk/event/beauty-expo-26/',
 'https://mktickets.mk/event/beauty-expo-26/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
 'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
 'https://mktickets.mk/event/vinca/',
 'https://mktickets.mk/event/vinca/',
 'https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/',
 'https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/',
 'https://mktickets.mk/event/d-festival-2026/',
 'https://mktickets.mk/event/d-festival-2026/',
 'https://mktickets.mk/event/autechre/',
 'https://mktickets.mk/event/autechre/',
 'https://mktickets.mk/event/ezhel-live-in-europe-2026/',
 'https://mktickets.mk/event/ezhel-live-in-europe-2026/',
 'https://mktickets.mk/event/fred-wesley-trio/',
 'https://mktickets.mk/event/fred-wesley-trio/',
 'https://mktickets.mk/event/fred-wesley-trio/',
 'https://mktickets.mk/event/fred-wesley-trio/',
 'https://mktickets.mk/event/fred-wesley-trio/',
 'https://mktickets.mk/event/fred-wesley-trio/',
 'https://mktickets.mk/event/fred-wesley-trio/',
 'https://mktickets.mk/event/fred-wesley-trio/',
 'https://mktickets.mk/event/fred-wesley-trio/',
 'https://mktickets.mk/event/ivan-bosiljcic-i-jelena-tomasevic-07-03-2026/',
 'https://mktickets.mk/event/ivan-bosiljcic-i-jelena-tomasevic-07-03-2026/',
 'https://mktickets.mk/event/ibjt/',
 'https://mktickets.mk/event/ibjt/',
 'https://mktickets.mk/event/jelena-tomasevic-ivan-bosiljcic-bitola/',
 'https://mktickets.mk/event/jelena-tomasevic-ivan-bosiljcic-bitola/',
 'https://mktickets.mk/event/jelena-tomasevic-ivan-bosiljcic-bt-10032026/',
 'https://mktickets.mk/event/jelena-tomasevic-ivan-bosiljcic-bt-10032026/',
 'https://mktickets.mk/event/d-festival-2026/',
 'https://mktickets.mk/event/d-festival-2026/',
 'https://mktickets.mk/event/d-festival-2026/',
 'https://mktickets.mk/event/d-festival-2026/',
 'https://mktickets.mk/event/d-festival-2026/',
 'https://mktickets.mk/event/tdm/',
 'https://mktickets.mk/event/tdm/',
 'https://mktickets.mk/event/tdm/',
 'https://mktickets.mk/event/tdm/',
 'https://mktickets.mk/event/tdm/',
 'https://mktickets.mk/event/tdm/',
 'https://mktickets.mk/event/dramskiteatar-2/',
 'https://mktickets.mk/event/dramskiteatar-2/',
 'https://mktickets.mk/event/glumcite-peat-2403/',
 'https://mktickets.mk/event/glumcite-peat-2403/',
 'https://mktickets.mk/event/glumcite-peat-2503/',
 'https://mktickets.mk/event/glumcite-peat-2503/',
 'https://mktickets.mk/event/sonuvame/',
 'https://mktickets.mk/event/sonuvame/',
 'https://mktickets.mk/event/sonuvame/',
 'https://mktickets.mk/event/sonuvame/',
 'https://mktickets.mk/event/sonuvame/',
 'https://mktickets.mk/event/sonuvame/',
 'https://mktickets.mk/event/sonuvame/',
 'https://mktickets.mk/event/metalkovci/',
 'https://mktickets.mk/event/metalkovci/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/njo-mike-holober/',
 'https://mktickets.mk/event/njo-mike-holober/',
 'https://mktickets.mk/event/milanova-igra/',
 'https://mktickets.mk/event/milanova-igra/',
 'https://mktickets.mk/event/makedonija-luxemburg/',
 'https://mktickets.mk/event/makedonija-luxemburg/',
 'https://mktickets.mk/event/makedonija-luxemburg/',
 'https://mktickets.mk/event/makedonija-luxemburg/',
 'https://mktickets.mk/event/makedonija-luxemburg/',
 'https://mktickets.mk/event/makedonija-luxemburg/',
 'https://mktickets.mk/event/zbm29/',
 'https://mktickets.mk/event/zbm29/',
 'https://mktickets.mk/event/zbm29/',
 'https://mktickets.mk/event/zbm29/',
 'https://mktickets.mk/event/zbm29/',
 'https://mktickets.mk/event/zbm29/',
 'https://mktickets.mk/event/snn27022026/',
 'https://mktickets.mk/event/snn27022026/',
 'https://mktickets.mk/event/snn13032026/',
 'https://mktickets.mk/event/snn13032026/',
 'https://mktickets.mk/event/ar/',
 'https://mktickets.mk/event/ar/',
 'https://mktickets.mk/event/beauty-expo-26/',
 'https://mktickets.mk/event/beauty-expo-26/']

In [14]:
df_detail_links = pd.DataFrame(data=detail_links, columns=["href"])

df_detail_links

                                              href
0    https://mktickets.mk/event/lord-of-the-dance/
1    https://mktickets.mk/event/lord-of-the-dance/
2    https://mktickets.mk/event/lord-of-the-dance/
3    https://mktickets.mk/event/lord-of-the-dance/
4    https://mktickets.mk/event/lord-of-the-dance/
..                                             ...
165        https://mktickets.mk/event/snn13032026/
166                 https://mktickets.mk/event/ar/
167                 https://mktickets.mk/event/ar/
168     https://mktickets.mk/event/beauty-expo-26/
169     https://mktickets.mk/event/beauty-expo-26/

[170 rows x 1 columns]

In [15]:
unique_detail_events = df_detail_links["href"].unique()

unique_detail_events

array(['https://mktickets.mk/event/lord-of-the-dance/',
       'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
       'https://mktickets.mk/event/the-young-gods/',
       'https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/',
       'https://mktickets.mk/event/joce-panov/',
       'https://mktickets.mk/event/tdm/',
       'https://mktickets.mk/event/dramskiteatar-2/',
       'https://mktickets.mk/event/zbm29/',
       'https://mktickets.mk/event/snn27022026/',
       'https://mktickets.mk/event/makedonija-luxemburg/',
       'https://mktickets.mk/event/fred-wesley-trio/',
       'https://mktickets.mk/event/sonuvame/',
       'https://mktickets.mk/event/ivan-bosiljcic-i-jelena-tomasevic-07-03-2026/',
       'https://mktickets.mk/event/metalkovci/',
       'https://mktickets.mk/event/ibjt/',
       'https://mktickets.mk/event/jelena-tomasevic-ivan-bosiljcic-bitola/',
       'https://mktickets.mk/event/jelena-tomasevic-ivan-bosiljcic-bt-10032026/',
       'https://mktickets.mk/event/tihomir-pop-asanovikj/',
       'https://mktickets.mk/event/snn13032026/',
       'https://mktickets.mk/event/ar/',
       'https://mktickets.mk/event/njo-mike-holober/',
       'https://mktickets.mk/event/glumcite-peat-2403/',
       'https://mktickets.mk/event/glumcite-peat-2503/',
       'https://mktickets.mk/event/milanova-igra/',
       'https://mktickets.mk/event/stefani-the-upper-room/',
       'https://mktickets.mk/event/ljubojna-25-godini/',
       'https://mktickets.mk/event/beauty-expo-26/',
       'https://mktickets.mk/event/vinca/',
       'https://mktickets.mk/event/d-festival-2026/',
       'https://mktickets.mk/event/autechre/',
       'https://mktickets.mk/event/ezhel-live-in-europe-2026/'],
      dtype=object)

In [16]:
len(unique_detail_events)

31

In [17]:
def scrape_event_detail(url):
    response = requests.get(url)
    if response.status_code != 200:
        print(f"Failed to fetch {url}")
        return None

    soup = BeautifulSoup(response.text, "html.parser")

    def clean_text(text):
        if not text:
         return None

        text = text.replace("\xa0", " ")
        text = text.replace("\n", " ")
        text = text.replace("\r", " ")

        text = re.sub(r"\s+", " ", text)
        return text.strip()

    title_tag = soup.select_one("div#event-details-container.row > :nth-child(2) > h2")
    image_tag = soup.select_one("div.event-main-image > img.wp-post-image")
    if image_tag and image_tag.get("src"):
        image_url = image_tag["src"]
    else:
        image_url = None
    # print(image_url)
    location_tag = soup.select_one("div.event-info > :nth-child(3) > small")
    price_tag = soup.select_one("div.festival-events > ul.tickets > li > p > :nth-child(2)")
    time_start_tag = soup.select_one("div.event-info > :nth-child(5) > :nth-child(2)")
    date_start_tag = soup.select_one("div.event-info > :nth-child(2) > :nth-child(2)")
    city_tag = soup.select_one("div.event-info > :nth-child(4) > :nth-child(2)")
    description_tag = soup.select_one("div.event-content")

    event = {
        "title": clean_text(title_tag.get_text()) if title_tag else None,
        "image_url": image_url if image_url else None,
        "location": clean_text(location_tag.get_text()) if location_tag else None,
        "price": clean_text(price_tag.get_text()).replace("Price:", "").strip() if price_tag else None,
        "time_start": clean_text(time_start_tag.get_text()) if time_start_tag else None,
        "date_start": clean_text(date_start_tag.get_text()) if date_start_tag else None,
        "city": clean_text(city_tag.get_text()) if city_tag else None,
        "description": clean_text(description_tag.get_text()) if description_tag else None,
    }

    return event

In [18]:
events = []

for link in unique_detail_events:
    event = scrape_event_detail(link)

    if event:
        events.append(event)

    len(events)

events

[{'title': 'LORD OF THE DANCE',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg',
  'location': 'Спортски центар „Јане Сандански”',
  'price': '1500-4500ден.',
  'time_start': '20:00',
  'date_start': '07-04-2026',
  'city': 'Скопје',
  'description': '30 години стоечки овации за ирскиот музичко-танцов спектакл! Lord Of The Dance, глобалниот феномен кој го редефинираше сценскиот танц, се враќа во Македонија на 7 април 2026 година со ново ексклузивно шоу за прослава на својата 30-годишнина! Овој значаен настан ветува дека ќе биде грандиозна прослава на трајното наследство на глобалната продукција која плени над 60 милиони обожаватели ширум светот. Не го пропуштајте магичното доживување што во Скопје ќе го приреди светски најпродаваниот танцов спектакл на сите времиња и фантастичната претстава на наградуваниот креатор и режисер Мајкл Флетли која продолжува да руши рекорди и да ја остава публиката без здив.'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png',
  'location': 'Спортски центар „Јане Сандански”',
  'price': '1400-2400ден.',
  'time_start': '20:00',
  'date_start': '09-04-2026',
  'city': 'Скопје',
  'description': 'ЈАКОВ ЈОЗИНОВИЌ ЗА ПРВПАТ ВО МАКЕДОНИЈА! Регионалната сензација Јаков Јозиновиќ ја најавува својата турнеја за 2026 година „Ja za čuda letim“, во чии рамки за првпат ќе настапи во Скопје – на 9 април во Арена „Јане Сандански“! Пред неколку дена Јаков го објави својот прв сингл „Polje ruža“, со кој најави ново поглавје во својата музичка кариера, а денес и официјално ја објавува својата голема регионална турнеја. Турнејата вклучува концерти во Арена Загреб, дури пет концерти во Сава Центар (Белград), како и настапи во Скопје, Нови Сад, Риека, Сплит, Осиек и Љубљана. По низа распродадени концерти и извонредни успеси во земјата и странство, Јаков Јозиновиќ уште еднаш докажува дека е една од најголемите сензации на современата музичка сцена во регионот.'},
 {'title': 'THE YOUNG GODS',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png',
  'location': 'Младински Културен Центар',
  'price': '1000ден.',
  'time_start': '20:30',
  'date_start': '14-03-2026',
  'city': 'Скопје',
  'description': 'Легендарното трио THE YOUNG GODS се враќа во Скопје! Во рамки на ТАКСИРАТ – концерт на пионерите на индустрискиот панк и електронскиот рок, со повеќедецениска репутација на култна појава на европската алтернативна сцена! Еволуцијата на звукот што го обликуваше идентитетот на авангардата сега добива ново поглавје — APPEAR DISAPPEAR, новиот, 14ти албум со кој The Young Gods ја започна обемната европска турнеја прославувајќи 40 години револуционерна музика!'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/01/640x4202.png',
  'location': 'С.Ц. Борис Трајковски',
  'price': '800-1800ден.',
  'time_start': '20:00',
  'date_start': '06-06-2026',
  'city': 'Скопје',
  'description': 'На 6 јуни 2026 година, во Арена „Борис Трајковски“ – Скопје, ќе се одржи голем концерт на Јован Јованов и Елвир Мекиќ, заедно со специјални гости. Публиката ќе има можност да ужива во најпознатите хитови, песни што обележаа едно време и создадоа незаборавни спомени. Dress code: WHITE Доколку можете ве покануваме да дојдете облечени во бело за подобро светлосно-визуелни ефекти и да бидете дел од оваа посебна вечер. Концертот е замислен како еднократен музички настан, исполнет со емоции, носталгија и врвна продукција. Инфо за високи маси: Ваучерот за високи маси вклучува 4 карти. Со купување на ваучерот, во рок од 48 часа ќе добиете линк на вашата е-маил адреса, преку кој ќе можете дополнително да докупите 1, 2 или 3 карти.'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/12/jp.png',
  'location': 'Македонска Филхармонија',
  'price': '500-700ден.',
  'time_start': '20:00',
  'date_start': '18-03-2026',
  'city': 'Скопје',
  'description': 'По исклучителниот успех и големиот интерес по повод 25-годишниот јубилеј, концертот на Јоце Панов во Македонската филхармонија прераснува во настан што публиката го побара повторно. Со гордост најавуваме ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2 Магијата продолжува. Уште една вечер исполнета со емоции, безвременска музика и моќен оркестарски звук кои се спојуваат во едно незаборавно доживување. Македонската филхармонија повторно ќе биде дом на музика што се памети, а Јоце Панов уште еднаш ќе ја потврди силната врска со својата публика. Кога традицијата ја создава публиката — таа трае.'},
 {'title': 'ТЕАТАР ЗА ДЕЦА И МЛАДИНЦИ – Месечен репертоар',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2019/02/90698676_3694511893954224_5091702799062794240_o_640x420.jpg',
  'location': '28-02-2026',
  'price': 'ден.',
  'time_start': 'Скопје',
  'date_start': '01-02-2026',
  'city': 'Театар за деца и младинци',
  'description': 'ТЕАТАРОТ ГО ЗАДРЖУВА ПРАВОТО ЗА ПРОМЕНА НА РЕПЕРТОАРОТ Замена на купените online ваучери се врши на билетарата во Театар за деца и младинци од вторник до недела.'},
 {'title': 'ДРАМСКИ ТЕАТАР – МЕСЕЧЕН РЕПЕРТОАР',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2019/01/Untitled-1-1.jpg',
  'location': '28-02-2026',
  'price': 'ден.',
  'time_start': 'Скопје',
  'date_start': '01-02-2026',
  'city': 'Драмски Театар Скопје',
  'description': 'Драмскиот театар – Скопје е една од најстарите театарски институции во Македонија. Располага со капацитет на големата сцена од 333 седишта и две ложи. ТЕАТАРОТ ГО ЗАДРЖУВА ПРАВОТО ЗА ПРОМЕНА НА РЕПЕРТОАРОТ'},
 {'title': 'Златна Бубамара на Популарноста #29',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/12/bubamara29.jpg',
  'location': 'С.Ц. Борис Трајковски',
  'price': '1500-2600ден.',
  'time_start': '20:00',
  'date_start': '26-02-2026',
  'city': 'Скопје',
  'description': 'На 72 часа пред 2 јануари се пуштени во продажба билетите за најновото издание на Златна бубамара на популарноста, Ве очекуваме со целата расположлива механизација … Под мотото „Апсолутна власт – апсолутна забава“, омилената манифестација – сатирично и музички ќе ја раскаже изминатата 2025 година, заедно со најпознатите уметници од Македонија, регионот и светот. Оваа година за прв пат на Златна Бубамара ќе имаме можност да видиме една голема светска музичка легенда со респектирачко музичко порфолио, која ќе ја откриеме на 10 дена пред настанот. Ќе се смееме, аплаудираме, пееме и играме во додега најспектакуларното издание на најголемото музичко шоу на Балканот. Секој посетител на своето седиште ќе има гратис Пролом вода и други подароци од нашите спонзори. Дослушање, догледање, Ваша, Радио Бубамара'},
 {'title': 'СИТЕ НАЈУБАВИ НЕШТА 27.02.2026',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/640x420-27mi-02.png',
  'location': 'Литература.мк -Дајмонд мол',
  'price': '500ден.',
  'time_start': '21:00',
  'date_start': '27-02-2026',
  'city': 'Скопје',
  'description': 'СИТЕ НАЈУБАВИ НЕШТА е монодрама работена според мотиви на Данкан МекМилан, во режија на Дејан Пројковски, a во продукција на ОХО. Ja изведува популарниот македонски актер Игор Ангелов. Монодрамата со оригинален наслов „Every Brilliant Thing“ на Данкан МекМилан ја повлекува завесата за тоа како е да се биде дете на родител, кој поминува низ тешки животни моменти и колку сме потребни за оние што ги сакаме. Заснована на вистинити и невистинити случки, оваа монодрама е приказна за тоа како да се постигне надеж во животот со фокус на најмалите нешта.'},
 {'title': None,
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/мкд-лух.png',
  'location': 'Спортска сала „Градски парк“',
  'price': '150-200ден.',
  'time_start': '18:00',
  'date_start': '27-02-2026',
  'city': 'Скопје',
  'description': None},
 {'title': 'FRED WESLEY TRIO',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/01/fwt.png',
  'location': 'Nightclub Pure',
  'price': '1300ден.',
  'time_start': '20:00',
  'date_start': '28-02-2026',
  'city': 'Скопје',
  'description': 'Импресивен архитект на фанк музиката, легендарниот тромбонист Фред Весли го враќа својот безвременски ритам на сцената со неговото Трио кој го носи срцето на класичниот фанк и џез повеќе од три децении. Од неговата пресвртница во работата како музички директор на Џејмс Браун, до неговата клучна улога во „Парламент-Фанкаделик“ на Џорџ Клинтон и соработките со икони како Реј Чарлс, Каунт Бејзи, Ван Морисон и Камео, влијанието на Весли е длабоко вкоренето низ историјата на фанкот, соулот и Р&Б. Одговорен за некои од најтрајните химни на фанкот – „House Party“, „Blow Your Head“, „Same Beat“, „Damn Right I Am Somebody“ и безброј други, Весли продолжува да го дефинира звукот на рутс фанкот со неодолива енергија и доминантно музицирање. Сега, во своите осумдесетти години, тој останува креативна сила, водејќи ги The New JBs со истиот оган што го поттикна сега легендарниот звук на ЏБ Хорнс, заедно со Масео Паркер и Пи Ви Елис. Со повеќе од десетина соло албуми, наследството на Весли е важно како и секогаш. Очекувајте прослава со тромбон и труба од еден од вистинските мајстори на фанкот. Еден од најголемите писатели и аранжери на фанк музика на планетата Земја.'},
 {'title': None,
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/sb.jpg',
  'location': 'Национална Oпера и Балет',
  'price': '28-02-2026',
  'time_start': '14:00',
  'date_start': '28-02-2026',
  'city': 'Скопје',
  'description': None},
 {'title': 'Ivan Bosiljčić i Jelena Tomašević 07.03.2026',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/7ji.png',
  'location': 'Македонска Филхармонија',
  'price': '1500-2000ден.',
  'time_start': '20:00',
  'date_start': '07-03-2026',
  'city': 'Скопје',
  'description': 'Поради големиот интерес и распродадениот прв концерт, отворен е нов датум – 7 март, втор концерт на Јелена Томашевиќ и Иван Босиљчиќ во придружба на симфониски оркестар. Вечер исполнета со љубов, емоции и врвна музика.'},
 {'title': 'МЕТАЛКОВЦИ – ПАТУВААТ!',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/metal.jpg',
  'location': 'Национална опера и балет – Мала сцена',
  'price': '400ден.',
  'time_start': '11:00',
  'date_start': '07-03-2026',
  'city': 'Skopje',
  'description': '„Металковци патуваат“ е интерактивна музичко-сценска претстава за деца и семејства, изведена од брас квинтет, која на едукативен и забавен начин ја приближува класичната и светската музика до најмладата публика. Преку сценска игра и музика во живо, публиката патува низ различни културни простори — од Франција и Италија, преку Мексико, Русија и Украина, до африканските ритми и македонската традиција. Претставата ги поттикнува децата активно да учествуваат преку движење, ритам и фантазија, додека истовремено се запознаваат со лимените дувачки инструменти и нивната звучна палета. Една од основните цели е креирање љубов меѓу децата и и лимените музички инструменти и агитирање кон децата за запишување во нижо музичко училиште и изучување на некој инструмент. Со својата интерактивна форма и современ пристап кон сценската едукација, „Металковци патуваат“ претставува спој на концерт и театар, создавајќи инспиративно музичко искуство кое ја развива љубопитноста, креативноста и љубовта кон уметноста кај младата публика'},
 {'title': 'Ivan Bosiljčić i Jelena Tomašević',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/12/ji.png',
  'location': 'Македонска Филхармонија',
  'price': '08-03-2026',
  'time_start': '20:00',
  'date_start': '08-03-2026',
  'city': 'Скопје',
  'description': 'Прославете го 8 Март со вечер исполнета со музичка топлина и искрени емоции. Со Симфонискиот оркестар на сцената, Jelena Tomašević и Ivan Bosiljčić ќе ви приредат вистинско концертно уживање.'},
 {'title': 'Jelena Tomasevic & Ivan Bosiljčić Битола',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/ivan-jelena-bt.png',
  'location': 'Центар за култура – Битола',
  'price': '1260ден.',
  'time_start': '20:00',
  'date_start': '09-03-2026',
  'city': 'Битола',
  'description': 'Со големо задоволство ве покануваме на прв заеднички концерт во Битола на Иван Босиљчиќ и Јелена Томашевиќ, во придружба на симфониски оркестар. Музичка вечер исполнета со емоции и врвна уметност, на 9 март во 20 часот, во Центарот за култура – Битола. Билетите се достапни на mktickets.mk и на билетарницата на Центарот за култура.'},
 {'title': 'Jelena Tomasevic & Ivan Bosiljčić Битола 10.03.2026',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/ијбт.png',
  'location': 'Центар за култура – Битола',
  'price': '1260ден.',
  'time_start': '20:00',
  'date_start': '10-03-2026',
  'city': 'Битола',
  'description': 'Со големо задоволство ве покануваме на вториот заеднички концерт во Битола на Иван Босиљчиќ и Јелена Томашевиќ, во придружба на симфониски оркестар. Музичка вечер исполнета со емоции и врвна уметност, на 10 март во 20 часот, во Центарот за култура – Битола. Билетите се достапни на mktickets.mk и на билетарницата на Центарот за култура.'},
 {'title': 'ТИХОМИР ПОП АСАНОВИЌ',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/10/tihomir2.png',
  'location': 'Македонска Филхармонија',
  'price': '1500ден.',
  'time_start': '20:00',
  'date_start': '10-03-2026',
  'city': 'Скопје',
  'description': 'Тихомир Поп Асановиќ- клавијатури, Јани Модер – соло гитара, Амир Гвиртзман- саксофон , Жига Кожар-тапани, Карин Землјиќ – вокал, Давор Чрнигој – бас , како и специјалните гости , Драги Јелиќ – гитара (ЈУ Група), Јован Мајоковиќ – саксофон, Рамбо Амадеус, Влатко Стефановски и Јан Стефановски .'},
 {'title': 'СИТЕ НАЈУБАВИ НЕШТА 13.03.2026',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/640x420-13ти-март.png',
  'location': 'Литература.мк -Дајмонд мол',
  'price': '500ден.',
  'time_start': '21:00',
  'date_start': '13-03-2026',
  'city': 'Скопје',
  'description': 'СИТЕ НАЈУБАВИ НЕШТА е монодрама работена според мотиви на Данкан МекМилан, во режија на Дејан Пројковски, a во продукција на ОХО. Ja изведува популарниот македонски актер Игор Ангелов. Монодрамата со оригинален наслов „Every Brilliant Thing“ на Данкан МекМилан ја повлекува завесата за тоа како е да се биде дете на родител, кој поминува низ тешки животни моменти и колку сме потребни за оние што ги сакаме. Заснована на вистинити и невистинити случки, оваа монодрама е приказна за тоа како да се постигне надеж во животот со фокус на најмалите нешта.'},
 {'title': 'Artist Republic – Регионална конвенција за тетовирање',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/Cover-Photo-ArtistRepublic.jpg',
  'location': '15-03-2026',
  'price': '14-03-2026',
  'time_start': 'Скопје',
  'date_start': '14-03-2026',
  'city': 'Хотел Александар Палас',
  'description': 'Artist Republic е регионална конвенција за тетовирање што ќе се одржи на 14 и 15 март во Хотел Александар Палас, Скопје. Ве очекува викенд исполнет со тетовирање во живо од 100+ уметници од целиот свет, натпревари и презентации, концерти, креативни работилници, штандови со уметност и опрема, и многу забава за сите љубители на tattoo културата.'},
 {'title': 'НАЦИОНАЛЕН ЏЕЗ ОРКЕСТАР СО MIKE HOLOBER',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/njo-mart.png',
  'location': 'Национална Oпера и Балет',
  'price': '1000ден.',
  'time_start': '20:00',
  'date_start': '18-03-2026',
  'city': 'Скопје',
  'description': 'НАЦИОНАЛЕН ЏЕЗ ОРКЕСТАР Mike Holober – диригент This Rock We’re On: Imaginary Letters 18 март | Национална опера и балет | 20:00 часот Солисти: Андријана Јаневска – вокал, Кирил Јосифов – виолончело, Влатко Нушев – вибрафон и перкусии На 18 март, Националниот џез оркестар ќе ја има ексклузивната чест да го изведе најновиот проект на Mike Holober – This Rock We’re On: Imaginary Letters, под диригентство на самиот автор. Mike Holober е еден од најзначајните современи џез композитори и аранжери, препознатлив по својата виртуозност, изразена оркестарска визија и длабока музичка чувствителност. Неговиот проект This Rock We’re On: Imaginary Letters е оценет како „монументално ремек-дело“ и „мајсторска лекција по композиција за џез оркестар“. Во ова дело, Holober создава впечатлив спој на два музички света, вметнувајќи ја суптилната естетика на современата класична музика, нагласена преку интимната камерна звучност на виолончелото, пијаното, вибрафонот и вокалот, во моќната и динамична енергија на биг бендот. Делото претставува длабока уметничка рефлексија за убавината на природата и судбината на планетата. Конципирано е како циклус од таканаречени „замислени писма“ посветени на писатели, уметници и активисти кои својот живот го поминале во восхит и грижа за планетата. Секое „писмо“ е проследено со инструментална оркестарска интерпретација што ја продлабочува и музички ја отсликува неговата содржина и поетска димензија. Овој концерт претставува ретка можност да се доживее комплексноста и длабочината на проектот на Holober во живо, под негово диригентство, во изведба на Националниот џез оркестар и специјалните гости. Ве покануваме да бидете дел од една исклучителна музичка вечер.'},
 {'title': 'Глумците Пеат 24.03',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/01/gpf.png',
  'location': 'Македонски Народен Театар',
  'price': '1000-1800ден.',
  'time_start': '20:00',
  'date_start': '24-03-2026',
  'city': 'Скопје',
  'description': '„Глумците ПЕАТ“ е ексклузивно сценско шоу, едно од најпосакуваните и најпосетувани сценски настани кај нас. Се одржува секоја година во март, во чест на 27 март, Светскиот ден на театарот и е уникатно без реприза. И оваа година подготвуваме забавно и уникатно шоу со многу глумци и уметници. Режисер: Дејан Пројковски Диригент: Љупчо Мирковски Кореограф: Олга Панго МНТ, 24 и 25 март 2026 година Почеток 20:00 часот'},
 {'title': 'Глумците Пеат 25.03',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/01/gpf.png',
  'location': 'Македонски Народен Театар',
  'price': '1000-1800ден.',
  'time_start': '20:00',
  'date_start': '25-03-2026',
  'city': 'Скопје',
  'description': '„Глумците ПЕАТ“ е ексклузивно сценско шоу, едно од најпосакуваните и најпосетувани сценски настани кај нас. Се одржува секоја година во март, во чест на 27 март, Светскиот ден на театарот и е уникатно без реприза. И оваа година подготвуваме забавно и уникатно шоу со многу глумци и уметници. Режисер: Дејан Пројковски Диригент: Љупчо Мирковски Кореограф: Олга Панго МНТ, 24 и 25 март 2026 година Почеток 20:00 часот'},
 {'title': '„Миланова игра“ – концерт во чест на Милан Завков',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/01/ми.png',
  'location': 'Македонска Филхармонија',
  'price': '800ден.',
  'time_start': '20:00',
  'date_start': '27-03-2026',
  'city': 'Скопје',

In [69]:
# Пример со реден број за да се види колку настани има вкупно.
events_ordering = []

for idx, link in enumerate(unique_detail_events, start=1):
    event = scrape_event_detail(link)
    if event:
        event['number'] = idx
        events.append(event)

events_ordering

[{'title': 'LORD OF THE DANCE',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg',
  'location': 'Спортски центар „Јане Сандански”',
  'price': '1500-4500ден.',
  'time_start': '20:00',
  'date_start': '07-04-2026',
  'city': 'Скопје',
  'description': '30 години стоечки овации за ирскиот музичко-танцов спектакл! Lord Of The Dance, глобалниот феномен кој го редефинираше сценскиот танц, се враќа во Македонија на 7 април 2026 година со ново ексклузивно шоу за прослава на својата 30-годишнина! Овој значаен настан ветува дека ќе биде грандиозна прослава на трајното наследство на глобалната продукција која плени над 60 милиони обожаватели ширум светот. Не го пропуштајте магичното доживување што во Скопје ќе го приреди светски најпродаваниот танцов спектакл на сите времиња и фантастичната претстава на наградуваниот креатор и режисер Мајкл Флетли која продолжува да руши рекорди и да ја остава публиката без здив.',
  'number': 1},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png',
  'location': 'Спортски центар „Јане Сандански”',
  'price': '1400-2400ден.',
  'time_start': '20:00',
  'date_start': '09-04-2026',
  'city': 'Скопје',
  'description': 'ЈАКОВ ЈОЗИНОВИЌ ЗА ПРВПАТ ВО МАКЕДОНИЈА! Регионалната сензација Јаков Јозиновиќ ја најавува својата турнеја за 2026 година „Ja za čuda letim“, во чии рамки за првпат ќе настапи во Скопје – на 9 април во Арена „Јане Сандански“! Пред неколку дена Јаков го објави својот прв сингл „Polje ruža“, со кој најави ново поглавје во својата музичка кариера, а денес и официјално ја објавува својата голема регионална турнеја. Турнејата вклучува концерти во Арена Загреб, дури пет концерти во Сава Центар (Белград), како и настапи во Скопје, Нови Сад, Риека, Сплит, Осиек и Љубљана. По низа распродадени концерти и извонредни успеси во земјата и странство, Јаков Јозиновиќ уште еднаш докажува дека е една од најголемите сензации на современата музичка сцена во регионот.',
  'number': 2},
 {'title': 'THE YOUNG GODS',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png',
  'location': 'Младински Културен Центар',
  'price': '1000ден.',
  'time_start': '20:30',
  'date_start': '14-03-2026',
  'city': 'Скопје',
  'description': 'Легендарното трио THE YOUNG GODS се враќа во Скопје! Во рамки на ТАКСИРАТ – концерт на пионерите на индустрискиот панк и електронскиот рок, со повеќедецениска репутација на култна појава на европската алтернативна сцена! Еволуцијата на звукот што го обликуваше идентитетот на авангардата сега добива ново поглавје — APPEAR DISAPPEAR, новиот, 14ти албум со кој The Young Gods ја започна обемната европска турнеја прославувајќи 40 години револуционерна музика!',
  'number': 3},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/01/640x4202.png',
  'location': 'С.Ц. Борис Трајковски',
  'price': '800-1800ден.',
  'time_start': '20:00',
  'date_start': '06-06-2026',
  'city': 'Скопје',
  'description': 'На 6 јуни 2026 година, во Арена „Борис Трајковски“ – Скопје, ќе се одржи голем концерт на Јован Јованов и Елвир Мекиќ, заедно со специјални гости. Публиката ќе има можност да ужива во најпознатите хитови, песни што обележаа едно време и создадоа незаборавни спомени. Dress code: WHITE Доколку можете ве покануваме да дојдете облечени во бело за подобро светлосно-визуелни ефекти и да бидете дел од оваа посебна вечер. Концертот е замислен како еднократен музички настан, исполнет со емоции, носталгија и врвна продукција. Инфо за високи маси: Ваучерот за високи маси вклучува 4 карти. Со купување на ваучерот, во рок од 48 часа ќе добиете линк на вашата е-маил адреса, преку кој ќе можете дополнително да докупите 1, 2 или 3 карти.',
  'number': 4},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/12/jp.png',
  'location': 'Македонска Филхармонија',
  'price': '500-700ден.',
  'time_start': '20:00',
  'date_start': '18-03-2026',
  'city': 'Скопје',
  'description': 'По исклучителниот успех и големиот интерес по повод 25-годишниот јубилеј, концертот на Јоце Панов во Македонската филхармонија прераснува во настан што публиката го побара повторно. Со гордост најавуваме ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2 Магијата продолжува. Уште една вечер исполнета со емоции, безвременска музика и моќен оркестарски звук кои се спојуваат во едно незаборавно доживување. Македонската филхармонија повторно ќе биде дом на музика што се памети, а Јоце Панов уште еднаш ќе ја потврди силната врска со својата публика. Кога традицијата ја создава публиката — таа трае.',
  'number': 5},
 {'title': 'ТЕАТАР ЗА ДЕЦА И МЛАДИНЦИ – Месечен репертоар',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2019/02/90698676_3694511893954224_5091702799062794240_o_640x420.jpg',
  'location': '28-02-2026',
  'price': 'ден.',
  'time_start': 'Скопје',
  'date_start': '01-02-2026',
  'city': 'Театар за деца и младинци',
  'description': 'ТЕАТАРОТ ГО ЗАДРЖУВА ПРАВОТО ЗА ПРОМЕНА НА РЕПЕРТОАРОТ Замена на купените online ваучери се врши на билетарата во Театар за деца и младинци од вторник до недела.',
  'number': 6},
 {'title': 'ДРАМСКИ ТЕАТАР – МЕСЕЧЕН РЕПЕРТОАР',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2019/01/Untitled-1-1.jpg',
  'location': '28-02-2026',
  'price': 'ден.',
  'time_start': 'Скопје',
  'date_start': '01-02-2026',
  'city': 'Драмски Театар Скопје',
  'description': 'Драмскиот театар – Скопје е една од најстарите театарски институции во Македонија. Располага со капацитет на големата сцена од 333 седишта и две ложи. ТЕАТАРОТ ГО ЗАДРЖУВА ПРАВОТО ЗА ПРОМЕНА НА РЕПЕРТОАРОТ',
  'number': 7},
 {'title': 'Златна Бубамара на Популарноста #29',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/12/bubamara29.jpg',
  'location': 'С.Ц. Борис Трајковски',
  'price': '1500-2600ден.',
  'time_start': '20:00',
  'date_start': '26-02-2026',
  'city': 'Скопје',
  'description': 'На 72 часа пред 2 јануари се пуштени во продажба билетите за најновото издание на Златна бубамара на популарноста, Ве очекуваме со целата расположлива механизација … Под мотото „Апсолутна власт – апсолутна забава“, омилената манифестација – сатирично и музички ќе ја раскаже изминатата 2025 година, заедно со најпознатите уметници од Македонија, регионот и светот. Оваа година за прв пат на Златна Бубамара ќе имаме можност да видиме една голема светска музичка легенда со респектирачко музичко порфолио, која ќе ја откриеме на 10 дена пред настанот. Ќе се смееме, аплаудираме, пееме и играме во додега најспектакуларното издание на најголемото музичко шоу на Балканот. Секој посетител на своето седиште ќе има гратис Пролом вода и други подароци од нашите спонзори. Дослушање, догледање, Ваша, Радио Бубамара',
  'number': 8},
 {'title': 'СИТЕ НАЈУБАВИ НЕШТА 27.02.2026',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/640x420-27mi-02.png',
  'location': 'Литература.мк -Дајмонд мол',
  'price': '500ден.',
  'time_start': '21:00',
  'date_start': '27-02-2026',
  'city': 'Скопје',
  'description': 'СИТЕ НАЈУБАВИ НЕШТА е монодрама работена според мотиви на Данкан МекМилан, во режија на Дејан Пројковски, a во продукција на ОХО. Ja изведува популарниот македонски актер Игор Ангелов. Монодрамата со оригинален наслов „Every Brilliant Thing“ на Данкан МекМилан ја повлекува завесата за тоа како е да се биде дете на родител, кој поминува низ тешки животни моменти и колку сме потребни за оние што ги сакаме. Заснована на вистинити и невистинити случки, оваа монодрама е приказна за тоа како да се постигне надеж во животот со фокус на најмалите нешта.',
  'number': 9},
 {'title': None,
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/мкд-лух.png',
  'location': 'Спортска сала „Градски парк“',
  'price': '150-200ден.',
  'time_start': '18:00',
  'date_start': '27-02-2026',
  'city': 'Скопје',
  'description': None,
  'number': 10},
 {'title': 'FRED WESLEY TRIO',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/01/fwt.png',
  'location': 'Nightclub Pure',
  'price': '1300ден.',
  'time_start': '20:00',
  'date_start': '28-02-2026',
  'city': 'Скопје',
  'description': 'Импресивен архитект на фанк музиката, легендарниот тромбонист Фред Весли го враќа својот безвременски ритам на сцената со неговото Трио кој го носи срцето на класичниот фанк и џез повеќе од три децении. Од неговата пресвртница во работата како музички директор на Џејмс Браун, до неговата клучна улога во „Парламент-Фанкаделик“ на Џорџ Клинтон и соработките со икони како Реј Чарлс, Каунт Бејзи, Ван Морисон и Камео, влијанието на Весли е длабоко вкоренето низ историјата на фанкот, соулот и Р&Б. Одговорен за некои од најтрајните химни на фанкот – „House Party“, „Blow Your Head“, „Same Beat“, „Damn Right I Am Somebody“ и безброј други, Весли продолжува да го дефинира звукот на рутс фанкот со неодолива енергија и доминантно музицирање. Сега, во своите осумдесетти години, тој останува креативна сила, водејќи ги The New JBs со истиот оган што го поттикна сега легендарниот звук на ЏБ Хорнс, заедно со Масео Паркер и Пи Ви Елис. Со повеќе од десетина соло албуми, наследството на Весли е важно како и секогаш. Очекувајте прослава со тромбон и труба од еден од вистинските мајстори на фанкот. Еден од најголемите писатели и аранжери на фанк музика на планетата Земја.',
  'number': 11},
 {'title': None,
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/sb.jpg',
  'location': 'Национална Oпера и Балет',
  'price': '28-02-2026',
  'time_start': '14:00',
  'date_start': '28-02-2026',
  'city': 'Скопје',
  'description': None,
  'number': 12},
 {'title': 'Ivan Bosiljčić i Jelena Tomašević 07.03.2026',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/7ji.png',
  'location': 'Македонска Филхармонија',
  'price': '1500-2000ден.',
  'time_start': '20:00',
  'date_start': '07-03-2026',
  'city': 'Скопје',
  'description': 'Поради големиот интерес и распродадениот прв концерт, отворен е нов датум – 7 март, втор концерт на Јелена Томашевиќ и Иван Босиљчиќ во придружба на симфониски оркестар. Вечер исполнета со љубов, емоции и врвна музика.',
  'number': 13},
 {'title': 'МЕТАЛКОВЦИ – ПАТУВААТ!',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/metal.jpg',
  'location': 'Национална опера и балет – Мала сцена',
  'price': '400ден.',
  'time_start': '11:00',
  'date_start': '07-03-2026',
  'city': 'Skopje',
  'description': '„Металковци патуваат“ е интерактивна музичко-сценска претстава за деца и семејства, изведена од брас квинтет, која на едукативен и забавен начин ја приближува класичната и светската музика до најмладата публика. Преку сценска игра и музика во живо, публиката патува низ различни културни простори — од Франција и Италија, преку Мексико, Русија и Украина, до африканските ритми и македонската традиција. Претставата ги поттикнува децата активно да учествуваат преку движење, ритам и фантазија, додека истовремено се запознаваат со лимените дувачки инструменти и нивната звучна палета. Една од основните цели е креирање љубов меѓу децата и и лимените музички инструменти и агитирање кон децата за запишување во нижо музичко училиште и изучување на некој инструмент. Со својата интерактивна форма и современ пристап кон сценската едукација, „Металковци патуваат“ претставува спој на концерт и театар, создавајќи инспиративно музичко искуство кое ја развива љубопитноста, креативноста и љубовта кон уметноста кај младата публика',
  'number': 14},
 {'title': 'Ivan Bosiljčić i Jelena Tomašević',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/12/ji.png',
  'location': 'Македонска Филхармонија',
  'price': '08-03-2026',
  'time_start': '20:00',
  'date_start': '08-03-2026',
  'city': 'Скопје',
  'description': 'Прославете го 8 Март со вечер исполнета со музичка топлина и искрени емоции. Со Симфонискиот оркестар на сцената, Jelena Tomašević и Ivan Bosiljčić ќе ви приредат вистинско концертно уживање.',
  'number': 15},
 {'title': 'Jelena Tomasevic & Ivan Bosiljčić Битола',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/ivan-jelena-bt.png',
  'location': 'Центар за култура – Битола',
  'price': '1260ден.',
  'time_start': '20:00',
  'date_start': '09-03-2026',
  'city': 'Битола',
  'description': 'Со големо задоволство ве покануваме на прв заеднички концерт во Битола на Иван Босиљчиќ и Јелена Томашевиќ, во придружба на симфониски оркестар. Музичка вечер исполнета со емоции и врвна уметност, на 9 март во 20 часот, во Центарот за култура – Битола. Билетите се достапни на mktickets.mk и на билетарницата на Центарот за култура.',
  'number': 16},
 {'title': 'Jelena Tomasevic & Ivan Bosiljčić Битола 10.03.2026',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/ијбт.png',
  'location': 'Центар за култура – Битола',
  'price': '1260ден.',
  'time_start': '20:00',
  'date_start': '10-03-2026',
  'city': 'Битола',
  'description': 'Со големо задоволство ве покануваме на вториот заеднички концерт во Битола на Иван Босиљчиќ и Јелена Томашевиќ, во придружба на симфониски оркестар. Музичка вечер исполнета со емоции и врвна уметност, на 10 март во 20 часот, во Центарот за култура – Битола. Билетите се достапни на mktickets.mk и на билетарницата на Центарот за култура.',
  'number': 17},
 {'title': 'ТИХОМИР ПОП АСАНОВИЌ',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/10/tihomir2.png',
  'location': 'Македонска Филхармонија',
  'price': '1500ден.',
  'time_start': '20:00',
  'date_start': '10-03-2026',
  'city': 'Скопје',
  'description': 'Тихомир Поп Асановиќ- клавијатури, Јани Модер – соло гитара, Амир Гвиртзман- саксофон , Жига Кожар-тапани, Карин Землјиќ – вокал, Давор Чрнигој – бас , како и специјалните гости , Драги Јелиќ – гитара (ЈУ Група), Јован Мајоковиќ – саксофон, Рамбо Амадеус, Влатко Стефановски и Јан Стефановски .',
  'number': 18},
 {'title': 'СИТЕ НАЈУБАВИ НЕШТА 13.03.2026',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/640x420-13ти-март.png',
  'location': 'Литература.мк -Дајмонд мол',
  'price': '500ден.',
  'time_start': '21:00',
  'date_start': '13-03-2026',
  'city': 'Скопје',
  'description': 'СИТЕ НАЈУБАВИ НЕШТА е монодрама работена според мотиви на Данкан МекМилан, во режија на Дејан Пројковски, a во продукција на ОХО. Ja изведува популарниот македонски актер Игор Ангелов. Монодрамата со оригинален наслов „Every Brilliant Thing“ на Данкан МекМилан ја повлекува завесата за тоа како е да се биде дете на родител, кој поминува низ тешки животни моменти и колку сме потребни за оние што ги сакаме. Заснована на вистинити и невистинити случки, оваа монодрама е приказна за тоа како да се постигне надеж во животот со фокус на најмалите нешта.',
  'number': 19},
 {'title': 'Artist Republic – Регионална конвенција за тетовирање',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/Cover-Photo-ArtistRepublic.jpg',
  'location': '15-03-2026',
  'price': '14-03-2026',
  'time_start': 'Скопје',
  'date_start': '14-03-2026',
  'city': 'Хотел Александар Палас',
  'description': 'Artist Republic е регионална конвенција за тетовирање што ќе се одржи на 14 и 15 март во Хотел Александар Палас, Скопје. Ве очекува викенд исполнет со тетовирање во живо од 100+ уметници од целиот свет, натпревари и презентации, концерти, креативни работилници, штандови со уметност и опрема, и многу забава за сите љубители на tattoo културата.',
  'number': 20},
 {'title': 'НАЦИОНАЛЕН ЏЕЗ ОРКЕСТАР СО MIKE HOLOBER',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/njo-mart.png',
  'location': 'Национална Oпера и Балет',
  'price': '1000ден.',
  'time_start': '20:00',
  'date_start': '18-03-2026',
  'city': 'Скопје',
  'description': 'НАЦИОНАЛЕН ЏЕЗ ОРКЕСТАР Mike Holober – диригент This Rock We’re On: Imaginary Letters 18 март | Национална опера и балет | 20:00 часот Солисти: Андријана Јаневска – вокал, Кирил Јосифов – виолончело, Влатко Нушев – вибрафон и перкусии На 18 март, Националниот џез оркестар ќе ја има ексклузивната чест да го изведе најновиот проект на Mike Holober – This Rock We’re On: Imaginary Letters, под диригентство на самиот автор. Mike Holober е еден од најзначајните современи џез композитори и аранжери, препознатлив по својата виртуозност, изразена оркестарска визија и длабока музичка чувствителност. Неговиот проект This Rock We’re On: Imaginary Letters е оценет како „монументално ремек-дело“ и „мајсторска лекција по композиција за џез оркестар“. Во ова дело, Holober создава впечатлив спој на два музички света, вметнувајќи ја суптилната естетика на современата класична музика, нагласена преку интимната камерна звучност на виолончелото, пијаното, вибрафонот и вокалот, во моќната и динамична енергија на биг бендот. Делото претставува длабока уметничка рефлексија за убавината на природата и судбината на планетата. Конципирано е како циклус од таканаречени „замислени писма“ посветени на писатели, уметници и активисти кои својот живот го поминале во восхит и грижа за планетата. Секое „писмо“ е проследено со инструментална оркестарска интерпретација што ја продлабочува и музички ја отсликува неговата содржина и поетска димензија. Овој концерт претставува ретка можност да се доживее комплексноста и длабочината на проектот на Holober во живо, под негово диригентство, во изведба на Националниот џез оркестар и специјалните гости. Ве покануваме да бидете дел од една исклучителна музичка вечер.',
  'number': 21},
 {'title': 'Глумците Пеат 24.03',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/01/gpf.png',
  'location': 'Македонски Народен Театар',
  'price': '1000-1800ден.',
  'time_start': '20:00',
  'date_start': '24-03-2026',
  'city': 'Скопје',
  'description': '„Глумците ПЕАТ“ е ексклузивно сценско шоу, едно од најпосакуваните и најпосетувани сценски настани кај нас. Се одржува секоја година во март, во чест на 27 март, Светскиот ден на театарот и е уникатно без реприза. И оваа година подготвуваме забавно и уникатно шоу со многу глумци и уметници. Режисер: Дејан Пројковски Диригент: Љупчо Мирковски Кореограф: Олга Панго МНТ, 24 и 25 март 2026 година Почеток 20:00 часот',
  'number': 22},
 {'title': 'Глумците Пеат 25.03',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/01/gpf.png',
  'location': 'Македонски Народен Театар',
  'price': '1000-1800ден.',
  'time_start': '20:00',
  'date_start': '25-03-2026',
  'city': 'Скопје',
  'description': '„Глумците ПЕАТ“ е ексклузивно сценско шоу, едно од најпосакуваните и најпосетувани сценски настани кај нас. Се одржува секоја година во март, во чест на 27 март, Светскиот ден на театарот и е уникатно без реприза. И оваа година подготвуваме забавно и уникатно шоу со многу глумци и уметници. Режисер: Дејан Пројковски Диригент: Љупчо Мирковски Кореограф: Олга Панго МНТ, 24 и 25 март 2026 година Почеток 20:00 часот',
  'number': 23},
 {'title': '„Миланова игра“ – концерт во чест на Милан Завков',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/01/ми.png',
  'location': 'Македонска Филхармонија',
  'price': '800ден.',
  'time_start': '20:00',
  'date_start': '27-03-2026',
  'city': 'Скопје',

In [20]:
folder = Path("..") / "events-output"
folder.mkdir(parents=True, exist_ok=True)

file_path = folder / "events.json"

with open(file_path, "w", encoding="utf-8") as f:
    json.dump(events, f, ensure_ascii=False, indent=2)

print(f"Saved {len(events)} events to {file_path.resolve()}")

Saved 31 events to D:\Workspace\EventsAggregator-Project\mktickets-scraper\events-output\events.json