In [56]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urljoin
from numpy import dtype
import re
import json
from pathlib import Path

In [57]:
BASE_URL = "https://mktickets.mk"

response = requests.get(BASE_URL)

response.status_code

200

In [58]:
html = response.text
html[522:579]

'<title>MKTickets - Buy Online Tickets : MKTickets</title>'

In [59]:
soup = BeautifulSoup(html, "html.parser")
soup.title

In [60]:
all_cards = soup.find_all("div")

len(all_cards)

239

In [61]:
all_cards[10].prettify()

'<div class="col-md-6 col-sm-12 col-xs-12 home-top-first home-top-col">\n <div class="slider-wrapper">\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/lord-of-the-dance/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" fetchpriority="high" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg" srcset="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg 640w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-250x164.jpg 250w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-120x79.jpg 120w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-2x1.jpg 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/lord-of-the-dance/">\n      LORD OF THE DANCE\n     </a>\n    </h3>\n    <p>\n     <span>\n      Спортски центар „Јане Сандански”, Скопје,\n     </span>\n     <span>\n      07-04-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png" srcset="https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png 640w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/">\n      ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“\n     </a>\n    </h3>\n    <p>\n     <span>\n      Спортски центар „Јане Сандански”, Скопје,\n     </span>\n     <span>\n      09-04-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/the-young-gods/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png" srcset="https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png 640w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/the-young-gods/">\n      THE YOUNG GODS\n     </a>\n    </h3>\n    <p>\n     <span>\n      Младински Културен Центар, Скопје,\n     </span>\n     <span>\n      14-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/joce-panov/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/12/jp.png" srcset="https://mktickets.mk/wp-content/uploads/2025/12/jp.png 640w, https://mktickets.mk/wp-content/uploads/2025/12/jp-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/12/jp-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/12/jp-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/joce-panov/">\n      ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2\n     </a>\n    </h3>\n    <p>\n     <span>\n      Македонска Филхармонија, Скопје,\n     </span>\n     <span>\n      18-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/ljubojna-25-godini/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets.png" srcset="https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets.png 640w, https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/ljubojna-25-godini/">\n      Љубојна – 25 години\n     </a>\n    </h3>\n    <p>\n     <span>\n      Македонска Филхармонија, Скопје,\n     </span>\n     <span>\n      29-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/lord-of-the-dance/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg" srcset="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg 640w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-250x164.jpg 250w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-120x79.jpg 120w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-2x1.jpg 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/lord-of-the-dance/">\n      LORD OF THE DANCE\n     </a>\n    </h3>\n    <p>\n     <span>\n      Спортски центар „Јане Сандански”, Скопје,\n     </span>\n     <span>\n      07-04-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png" srcset="https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png 640w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/">\n      ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“\n     </a>\n    </h3>\n    <p>\n     <span>\n      Спортски центар „Јане Сандански”, Скопје,\n     </span>\n     <span>\n      09-04-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/the-young-gods/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png" srcset="https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png 640w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/the-young-gods/">\n      THE YOUNG GODS\n     </a>\n    </h3>\n    <p>\n     <span>\n      Младински Културен Центар, Скопје,\n     </span>\n     <span>\n      14-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/joce-panov/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/12/jp.png" srcset="https://mktickets.mk/wp-content/uploads/2025/12/jp.png 640w, https://mktickets.mk/wp-content/uploads/2025/12/jp-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/12/jp-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/12/jp-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/joce-panov/">\n      ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2\n     </a>\n    </h3>\n    <p>\n     <span>\n      Македонска Филхармонија, Скопје,\n     </span>\n     <span>\n      18-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/ljubojna-25-godini/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets.png" srcset="https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets.png 640w, https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/ljubojna-25-godini/">\n      Љубојна – 25 години\n     </a>\n    </h3>\n    <p>\n     <span>\n      Македонска Филхармонија, Скопје,\n     </span>\n     <span>\n      29-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/lord-of-the-dance/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg" srcset="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg 640w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-250x164.jpg 250w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-120x79.jpg 120w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-2x1.jpg 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/lord-of-the-dance/">\n      LORD OF THE DANCE\n     </a>\n    </h3>\n    <p>\n     <span>\n      Спортски центар „Јане Сандански”, Скопје,\n     </span>\n     <span>\n      07-04-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png" srcset="https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png 640w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/">\n      ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“\n     </a>\n    </h3>\n    <p>\n     <span>\n      Спортски центар „Јане Сандански”, Скопје,\n     </span>\n     <span>\n      09-04-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/the-young-gods/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png" srcset="https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png 640w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/the-young-gods/">\n      THE YOUNG GODS\n     </a>\n    </h3>\n    <p>\n     <span>\n      Младински Културен Центар, Скопје,\n     </span>\n     <span>\n      14-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/joce-panov/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/12/jp.png" srcset="https://mktickets.mk/wp-content/uploads/2025/12/jp.png 640w, https://mktickets.mk/wp-content/uploads/2025/12/jp-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/12/jp-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/12/jp-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/joce-panov/">\n      ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2\n     </a>\n    </h3>\n    <p>\n     <span>\n      Македонска Филхармонија, Скопје,\n     </span>\n     <span>\n      18-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/ljubojna-25-godini/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets.png" srcset="https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets.png 640w, https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/ljubojna-25-godini/">\n      Љубојна – 25 години\n     </a>\n    </h3>\n    <p>\n     <span>\n      Македонска Филхармонија, Скопје,\n     </span>\n     <span>\n      29-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/lord-of-the-dance/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg" srcset="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg 640w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-250x164.jpg 250w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-120x79.jpg 120w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-2x1.jpg 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/lord-of-the-dance/">\n      LORD OF THE DANCE\n     </a>\n    </h3>\n    <p>\n     <span>\n      Спортски центар „Јане Сандански”, Скопје,\n     </span>\n     <span>\n      07-04-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png" srcset="https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png 640w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/12/jjbaner-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/">\n      ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“\n     </a>\n    </h3>\n    <p>\n     <span>\n      Спортски центар „Јане Сандански”, Скопје,\n     </span>\n     <span>\n      09-04-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/the-young-gods/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png" srcset="https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png 640w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/10/young-gods-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/the-young-gods/">\n      THE YOUNG GODS\n     </a>\n    </h3>\n    <p>\n     <span>\n      Младински Културен Центар, Скопје,\n     </span>\n     <span>\n      14-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/joce-panov/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/12/jp.png" srcset="https://mktickets.mk/wp-content/uploads/2025/12/jp.png 640w, https://mktickets.mk/wp-content/uploads/2025/12/jp-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2025/12/jp-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2025/12/jp-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/joce-panov/">\n      ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2\n     </a>\n    </h3>\n    <p>\n     <span>\n      Македонска Филхармонија, Скопје,\n     </span>\n     <span>\n      18-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/ljubojna-25-godini/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets.png" srcset="https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets.png 640w, https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets-250x164.png 250w, https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets-120x79.png 120w, https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets-2x1.png 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/ljubojna-25-godini/">\n      Љубојна – 25 години\n     </a>\n    </h3>\n    <p>\n     <span>\n      Македонска Филхармонија, Скопје,\n     </span>\n     <span>\n      29-03-2026\n     </span>\n    </p>\n   </div>\n  </div>\n  <div class="event-container">\n   <a class="poster-link" href="https://mktickets.mk/event/lord-of-the-dance/">\n    <img alt="" class="attachment-poster-featured size-poster-featured wp-post-image" decoding="async" sizes="(max-width: 640px) 100vw, 640px" src="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg" srcset="https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg 640w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-250x164.jpg 250w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-120x79.jpg 120w, https://mktickets.mk/wp-content/uploads/2025/10/mkticks-2x1.jpg 2w"/>\n   </a>\n   <div class="event-hover">\n    <h3>\n     <a href="https://mktickets.mk/event/lord-of-the-dance/">\n      LORD OF THE DANCE\n     </a>\n    </h3>\n    <p>\n     <span>\n      Спортски центар „Јане Сандански”, Скопје,\n     </span>\n     <span>\n      07-04-2026\n     </sp

In [62]:
events_titles = []

for card in all_cards[:]:
    title_tag = card.select_one("div.event-hover > h3")

    if not title_tag:
        continue

    event = {
        "title": title_tag.text.strip()
    }

    events_titles.append(event)

events_titles

[{'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'Љубојна – 25 години'},
 {'title': 'Љубојна – 25 години'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'Љубојна – 25 години'},
 {'title': 'Љубојна – 25 години'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'Љубојна – 25 години'},
 {'title': 'Љубојна – 25 години'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'Љубојна – 25 години'},
 {'title': 'Љубојна – 25 години'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'Љубојна – 25 години'},
 {'title': 'Љубојна – 25 години'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'THE YOUNG GODS'},
 {'title': 'Љубојна – 25 години'},
 {'title': 'Љубојна – 25 години'},
 {'title': 'КК МЗТ Скопје Аеродром – КК Тиквеш'},
 {'title': 'КК МЗТ Скопје Аеродром – КК Тиквеш'},
 {'title': 'КК МЗТ Скопје Аеродром – КК Тиквеш'},
 {'title': 'КК МЗТ Скопје Аеродром – КК Тиквеш'},
 {'title': 'КК МЗТ Скопје Аеродром – КК Тиквеш'},
 {'title': 'КК МЗТ Скопје Аеродром – КК Тиквеш'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2'},
 {'title': 'НАЦИОНАЛЕН ЏЕЗ ОРКЕСТАР СО MIKE HOLOBER'},
 {'title': 'НАЦИОНАЛЕН ЏЕЗ ОРКЕСТАР СО MIKE HOLOBER'},
 {'title': 'НАЦИОНАЛЕН ЏЕЗ ОРКЕСТАР СО MIKE HOLOBER'},
 {'title': 'Глумците Пеат 24.03'},
 {'title': 'Глумците Пеат 24.03'},
 {'title': 'Глумците Пеат 24.03'},
 {'title': 'Глумците Пеат 25.03'},
 {'title': 'Глумците Пеат 25.03'},
 {'title': 'Глумците Пеат 25.03'},
 {'title': '„Миланова игра“ – концерт во чест на Милан Завков'},
 {'title': '„Миланова игра“ – концерт во чест на Милан Завков'},
 {'title': '„Миланова игра“ – концерт во чест на Милан Завков'},
 {'title': 'GrandVin 2026'},
 {'title': 'GrandVin 2026'},
 {'title': 'GrandVin 2026'},
 {'title': 'STEFANI & THE UPPER ROOM'},
 {'title': 'STEFANI & THE UPPER ROOM'},
 {'title': 'STEFANI & THE UPPER ROOM'},
 {'title': 'Љубојна – 25 години'},
 {'title': 'Љубојна – 25 години'},
 {'title': 'Љубојна – 25 години'},
 {'title': 'Beauty Expo ’26'},
 {'title': 'Beauty Expo ’26'},
 {'title': 'Beauty Expo ’26'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'LORD OF THE DANCE'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“'},
 {'title': 'ПОТОЧИЊА 2026'},
 {'title': 'ПОТОЧИЊА 2026'},
 {'title': 'ПОТОЧИЊА 2026'},
 {'title': 'Cafe De Anatolia SHOW'},
 {'title': 'Cafe De Anatolia SHOW'},
 {'title': 'Cafe De Anatolia SHOW'},
 {'title': 'Горан Винчиќ Винча – Комедијата е сериозна работа'},
 {'title': 'Горан Винчиќ Винча – Комедијата е сериозна работа'},
 {'title': 'Горан Винчиќ Винча – Комедијата е сериозна работа'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите'},
 {'title': 'Д фестивал 2026'},
 {'title': 'Д фестивал 2026'},
 {'title': 'Д фестивал 2026'},
 {'title': 'СФЕСТ ФЕСТИВАЛ'},
 {'title': 'СФЕСТ ФЕСТИВАЛ'},
 {'title': 'СФЕСТ ФЕСТИВАЛ'},
 {'title': 'AUTECHRE'},
 {'title': 'AUTECHRE'},
 {'title': 'AUTECHRE'},
 {'title': 'Ezhel Live in Europe 2026'},
 {'title': 'Ezhel Live in Europe 2026'},
 {'title': 'Ezhel Live in Europe 2026'}]

In [63]:
len(events_titles)

128

In [64]:
df_events_titles = pd.DataFrame(data=events_titles)

df_events_titles

                         title
0            LORD OF THE DANCE
1            LORD OF THE DANCE
2            LORD OF THE DANCE
3            LORD OF THE DANCE
4            LORD OF THE DANCE
..                         ...
123                   AUTECHRE
124                   AUTECHRE
125  Ezhel Live in Europe 2026
126  Ezhel Live in Europe 2026
127  Ezhel Live in Europe 2026

[128 rows x 1 columns]

In [65]:
unique_events_titles = df_events_titles["title"].unique()

unique_events_titles

array(['LORD OF THE DANCE', 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“',
       'THE YOUNG GODS', 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2',
       'Љубојна – 25 години', 'КК МЗТ Скопје Аеродром – КК Тиквеш',
       'НАЦИОНАЛЕН ЏЕЗ ОРКЕСТАР СО MIKE HOLOBER', 'Глумците Пеат 24.03',
       'Глумците Пеат 25.03',
       '„Миланова игра“ – концерт во чест на Милан Завков',
       'GrandVin 2026', 'STEFANI & THE UPPER ROOM', 'Beauty Expo ’26',
       'ПОТОЧИЊА 2026', 'Cafe De Anatolia SHOW',
       'Горан Винчиќ Винча – Комедијата е сериозна работа',
       'Јован Јованов, Елвир Мекиќ и пријателите', 'Д фестивал 2026',
       'СФЕСТ ФЕСТИВАЛ', 'AUTECHRE', 'Ezhel Live in Europe 2026'],
      dtype=object)

In [66]:
len(unique_events_titles)

21

In [67]:
detail_links = []

for card in all_cards:
    a = card.select_one("a.poster-link")
    if a and a.get("href"):

        detail_links.append(a["href"])

detail_links

['https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
 'https://mktickets.mk/event/the-young-gods/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/ljubojna-25-godini/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
 'https://mktickets.mk/event/the-young-gods/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/ljubojna-25-godini/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
 'https://mktickets.mk/event/the-young-gods/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/ljubojna-25-godini/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
 'https://mktickets.mk/event/the-young-gods/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/ljubojna-25-godini/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
 'https://mktickets.mk/event/the-young-gods/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/ljubojna-25-godini/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
 'https://mktickets.mk/event/the-young-gods/',
 'https://mktickets.mk/event/the-young-gods/',
 'https://mktickets.mk/event/ljubojna-25-godini/',
 'https://mktickets.mk/event/mzt-skopje-aerodrom-tikvesh/',
 'https://mktickets.mk/event/mzt-skopje-aerodrom-tikvesh/',
 'https://mktickets.mk/event/mzt-skopje-aerodrom-tikvesh/',
 'https://mktickets.mk/event/mzt-skopje-aerodrom-tikvesh/',
 'https://mktickets.mk/event/mzt-skopje-aerodrom-tikvesh/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/njo-mike-holober/',
 'https://mktickets.mk/event/njo-mike-holober/',
 'https://mktickets.mk/event/glumcite-peat-2403/',
 'https://mktickets.mk/event/glumcite-peat-2403/',
 'https://mktickets.mk/event/glumcite-peat-2503/',
 'https://mktickets.mk/event/glumcite-peat-2503/',
 'https://mktickets.mk/event/milanova-igra/',
 'https://mktickets.mk/event/milanova-igra/',
 'https://mktickets.mk/event/grandvin-2026/',
 'https://mktickets.mk/event/grandvin-2026/',
 'https://mktickets.mk/event/stefani-the-upper-room/',
 'https://mktickets.mk/event/stefani-the-upper-room/',
 'https://mktickets.mk/event/ljubojna-25-godini/',
 'https://mktickets.mk/event/ljubojna-25-godini/',
 'https://mktickets.mk/event/beauty-expo-26/',
 'https://mktickets.mk/event/beauty-expo-26/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
 'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
 'https://mktickets.mk/event/potochinja-2026/',
 'https://mktickets.mk/event/potochinja-2026/',
 'https://mktickets.mk/event/cafe-de-anatolia-show/',
 'https://mktickets.mk/event/cafe-de-anatolia-show/',
 'https://mktickets.mk/event/vinca/',
 'https://mktickets.mk/event/vinca/',
 'https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/',
 'https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/',
 'https://mktickets.mk/event/d-festival-2026/',
 'https://mktickets.mk/event/d-festival-2026/',
 'https://mktickets.mk/event/sfest/',
 'https://mktickets.mk/event/sfest/',
 'https://mktickets.mk/event/autechre/',
 'https://mktickets.mk/event/autechre/',
 'https://mktickets.mk/event/ezhel-live-in-europe-2026/',
 'https://mktickets.mk/event/ezhel-live-in-europe-2026/',
 'https://mktickets.mk/event/stefani-the-upper-room/',
 'https://mktickets.mk/event/stefani-the-upper-room/',
 'https://mktickets.mk/event/stefani-the-upper-room/',
 'https://mktickets.mk/event/stefani-the-upper-room/',
 'https://mktickets.mk/event/stefani-the-upper-room/',
 'https://mktickets.mk/event/stefani-the-upper-room/',
 'https://mktickets.mk/event/stefani-the-upper-room/',
 'https://mktickets.mk/event/stefani-the-upper-room/',
 'https://mktickets.mk/event/stefani-the-upper-room/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/lord-of-the-dance/',
 'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
 'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
 'https://mktickets.mk/event/cafe-de-anatolia-show/',
 'https://mktickets.mk/event/cafe-de-anatolia-show/',
 'https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/',
 'https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/',
 'https://mktickets.mk/event/d-festival-2026/',
 'https://mktickets.mk/event/d-festival-2026/',
 'https://mktickets.mk/event/d-festival-2026/',
 'https://mktickets.mk/event/d-festival-2026/',
 'https://mktickets.mk/event/d-festival-2026/',
 'https://mktickets.mk/event/sfest/',
 'https://mktickets.mk/event/sfest/',
 'https://mktickets.mk/event/glumcite-peat-2403/',
 'https://mktickets.mk/event/glumcite-peat-2403/',
 'https://mktickets.mk/event/glumcite-peat-2403/',
 'https://mktickets.mk/event/glumcite-peat-2403/',
 'https://mktickets.mk/event/glumcite-peat-2403/',
 'https://mktickets.mk/event/glumcite-peat-2403/',
 'https://mktickets.mk/event/glumcite-peat-2503/',
 'https://mktickets.mk/event/glumcite-peat-2503/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/joce-panov/',
 'https://mktickets.mk/event/njo-mike-holober/',
 'https://mktickets.mk/event/njo-mike-holober/',
 'https://mktickets.mk/event/milanova-igra/',
 'https://mktickets.mk/event/milanova-igra/',
 'https://mktickets.mk/event/ljubojna-25-godini/',
 'https://mktickets.mk/event/ljubojna-25-godini/',
 'https://mktickets.mk/event/mzt-skopje-aerodrom-tikvesh/',
 'https://mktickets.mk/event/mzt-skopje-aerodrom-tikvesh/',
 'https://mktickets.mk/event/mzt-skopje-aerodrom-tikvesh/',
 'https://mktickets.mk/event/mzt-skopje-aerodrom-tikvesh/',
 'https://mktickets.mk/event/mzt-skopje-aerodrom-tikvesh/',
 'https://mktickets.mk/event/mzt-skopje-aerodrom-tikvesh/',
 'https://mktickets.mk/event/grandvin-2026/',
 'https://mktickets.mk/event/grandvin-2026/',
 'https://mktickets.mk/event/grandvin-2026/',
 'https://mktickets.mk/event/grandvin-2026/',
 'https://mktickets.mk/event/grandvin-2026/',
 'https://mktickets.mk/event/grandvin-2026/',
 'https://mktickets.mk/event/beauty-expo-26/',
 'https://mktickets.mk/event/beauty-expo-26/',
 'https://mktickets.mk/event/potochinja-2026/',
 'https://mktickets.mk/event/potochinja-2026/',
 'https://mktickets.mk/event/vinca/',
 'https://mktickets.mk/event/vinca/']

In [68]:
df_detail_links = pd.DataFrame(data=detail_links, columns=["href"])

df_detail_links

                                              href
0    https://mktickets.mk/event/lord-of-the-dance/
1    https://mktickets.mk/event/lord-of-the-dance/
2    https://mktickets.mk/event/lord-of-the-dance/
3    https://mktickets.mk/event/lord-of-the-dance/
4    https://mktickets.mk/event/lord-of-the-dance/
..                                             ...
137     https://mktickets.mk/event/beauty-expo-26/
138    https://mktickets.mk/event/potochinja-2026/
139    https://mktickets.mk/event/potochinja-2026/
140              https://mktickets.mk/event/vinca/
141              https://mktickets.mk/event/vinca/

[142 rows x 1 columns]

In [69]:
unique_detail_events = df_detail_links["href"].unique()

unique_detail_events

array(['https://mktickets.mk/event/lord-of-the-dance/',
       'https://mktickets.mk/event/jakov-jozinovic-ja-za-cuda-letim/',
       'https://mktickets.mk/event/the-young-gods/',
       'https://mktickets.mk/event/joce-panov/',
       'https://mktickets.mk/event/ljubojna-25-godini/',
       'https://mktickets.mk/event/mzt-skopje-aerodrom-tikvesh/',
       'https://mktickets.mk/event/njo-mike-holober/',
       'https://mktickets.mk/event/glumcite-peat-2403/',
       'https://mktickets.mk/event/glumcite-peat-2503/',
       'https://mktickets.mk/event/milanova-igra/',
       'https://mktickets.mk/event/grandvin-2026/',
       'https://mktickets.mk/event/stefani-the-upper-room/',
       'https://mktickets.mk/event/beauty-expo-26/',
       'https://mktickets.mk/event/potochinja-2026/',
       'https://mktickets.mk/event/cafe-de-anatolia-show/',
       'https://mktickets.mk/event/vinca/',
       'https://mktickets.mk/event/jovan-jovanov-elvir-mekic-i-prijateli/',
       'https://mktickets.mk/event/d-festival-2026/',
       'https://mktickets.mk/event/sfest/',
       'https://mktickets.mk/event/autechre/',
       'https://mktickets.mk/event/ezhel-live-in-europe-2026/'],
      dtype=object)

In [70]:
len(unique_detail_events)

21

In [71]:
def scrape_event_detail(url):
    response = requests.get(url)
    if response.status_code != 200:
        print(f"Failed to fetch {url}")
        return None

    soup = BeautifulSoup(response.text, "html.parser")

    def clean_text(text):
        if not text:
         return None

        text = text.replace("\xa0", " ")
        text = text.replace("\n", " ")
        text = text.replace("\r", " ")

        text = re.sub(r"\s+", " ", text)
        return text.strip()

    title_tag = soup.select_one("div.event-top-main > h1")
    # title_tag = soup.select_one("div#event-details-container.row > :nth-child(2) > h2")
    image_tag = soup.select_one("div.event-main-image > img.wp-post-image")
    if image_tag and image_tag.get("src"):
        image_url = image_tag["src"]
    else:
        image_url = None
    # print(image_url)
    location_tag = soup.select_one("div.event-info > :nth-child(3) > small")
    price_tag = soup.select_one("div.festival-events > ul.tickets > li > p > :nth-child(2)")
    time_start_tag = soup.select_one("div.event-info > :nth-child(5) > :nth-child(2)")
    date_start_tag = soup.select_one("div.event-info > :nth-child(2) > :nth-child(2)")
    city_tag = soup.select_one("div.event-info > :nth-child(4) > :nth-child(2)")
    description_tag = soup.select_one("div.event-content")

    event = {
        "title": clean_text(title_tag.get_text()) if title_tag else None,
        "image_url": image_url if image_url else None,
        "location": clean_text(location_tag.get_text()) if location_tag else None,
        "price": clean_text(price_tag.get_text()).replace("Price:", "").strip() if price_tag else None,
        "time_start": clean_text(time_start_tag.get_text()) if time_start_tag else None,
        "date_start": clean_text(date_start_tag.get_text()) if date_start_tag else None,
        "city": clean_text(city_tag.get_text()) if city_tag else None,
        "description": clean_text(description_tag.get_text()) if description_tag else None,
    }

    return event

In [72]:
events = []

for link in unique_detail_events:
    event = scrape_event_detail(link)

    if event:
        events.append(event)

    len(events)

events

[{'title': 'LORD OF THE DANCE',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/10/mkticks.jpg',
  'location': 'Спортски центар „Јане Сандански”',
  'price': '1500-4500ден.',
  'time_start': '20:00',
  'date_start': '07-04-2026',
  'city': 'Скопје',
  'description': '30 години стоечки овации за ирскиот музичко-танцов спектакл! Lord Of The Dance, глобалниот феномен кој го редефинираше сценскиот танц, се враќа во Македонија на 7 април 2026 година со ново ексклузивно шоу за прослава на својата 30-годишнина! Овој значаен настан ветува дека ќе биде грандиозна прослава на трајното наследство на глобалната продукција која плени над 60 милиони обожаватели ширум светот. Не го пропуштајте магичното доживување што во Скопје ќе го приреди светски најпродаваниот танцов спектакл на сите времиња и фантастичната претстава на наградуваниот креатор и режисер Мајкл Флетли која продолжува да руши рекорди и да ја остава публиката без здив.'},
 {'title': 'ЈАКОВ ЈОЗИНОВИЌ „Ja za čuda letim“',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/12/jjbaner.png',
  'location': 'Спортски центар „Јане Сандански”',
  'price': '1400-2400ден.',
  'time_start': '20:00',
  'date_start': '09-04-2026',
  'city': 'Скопје',
  'description': 'ЈАКОВ ЈОЗИНОВИЌ ЗА ПРВПАТ ВО МАКЕДОНИЈА! Регионалната сензација Јаков Јозиновиќ ја најавува својата турнеја за 2026 година „Ja za čuda letim“, во чии рамки за првпат ќе настапи во Скопје – на 9 април во Арена „Јане Сандански“! Пред неколку дена Јаков го објави својот прв сингл „Polje ruža“, со кој најави ново поглавје во својата музичка кариера, а денес и официјално ја објавува својата голема регионална турнеја. Турнејата вклучува концерти во Арена Загреб, дури пет концерти во Сава Центар (Белград), како и настапи во Скопје, Нови Сад, Риека, Сплит, Осиек и Љубљана. По низа распродадени концерти и извонредни успеси во земјата и странство, Јаков Јозиновиќ уште еднаш докажува дека е една од најголемите сензации на современата музичка сцена во регионот.'},
 {'title': 'THE YOUNG GODS',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/10/young-gods.png',
  'location': 'Младински Културен Центар',
  'price': '1500ден.',
  'time_start': '20:30',
  'date_start': '14-03-2026',
  'city': 'Скопје',
  'description': 'Легендарното трио THE YOUNG GODS се враќа во Скопје! Во рамки на ТАКСИРАТ – концерт на пионерите на индустрискиот панк и електронскиот рок, со повеќедецениска репутација на култна појава на европската алтернативна сцена! Еволуцијата на звукот што го обликуваше идентитетот на авангардата сега добива ново поглавје — APPEAR DISAPPEAR, новиот, 14ти албум со кој The Young Gods ја започна обемната европска турнеја прославувајќи 40 години револуционерна музика!'},
 {'title': 'ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/12/jp.png',
  'location': 'Македонска Филхармонија',
  'price': '500-700ден.',
  'time_start': '20:00',
  'date_start': '18-03-2026',
  'city': 'Скопје',
  'description': 'По исклучителниот успех и големиот интерес по повод 25-годишниот јубилеј, концертот на Јоце Панов во Македонската филхармонија прераснува во настан што публиката го побара повторно. Со гордост најавуваме ЈОЦЕ ПАНОВ – МАКЕДОНСКА ФИЛХАРМОНИЈА 2 Магијата продолжува. Уште една вечер исполнета со емоции, безвременска музика и моќен оркестарски звук кои се спојуваат во едно незаборавно доживување. Македонската филхармонија повторно ќе биде дом на музика што се памети, а Јоце Панов уште еднаш ќе ја потврди силната врска со својата публика. Кога традицијата ја создава публиката — таа трае.'},
 {'title': 'Љубојна – 25 години',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/Ljubojna-mktickets.png',
  'location': 'Македонска Филхармонија',
  'price': '1000-1500ден.',
  'time_start': '20:00',
  'date_start': '29-03-2026',
  'city': 'Скопје',
  'description': '25 години безвременска музика – ЉУБОЈНА во својот препознатлив манир прославува јубилеј со ново големо целовечерно концертно издание во Скопје! 29 МАРТ 2026 ФИЛХАРМОНИЈА Еден од водечките музички брендови на Македонија својата музика ја свири страсно, со енергија на рок бенд и тоа во сите нејзини форми: нејзината изворна, класична, популарна, експериментална форма. Ја соопштува преку фантастичната вокална експресија на Вера Милошевска која заедно со Оливер Јосифовски (контрабасист, композитор и продуцент) веќе 25 години се симбол и синоним за ЉУБОЈНА. Експериментирајќи и истражувајќи, Љубојна постојано ја освежува музиката одново и одново, одржувајќи го звукот модерен, моќен, кадифен, елегантен и енергичен. Концерт на кој заедно го славиме македонскиот културен феномен кој најавтентично го пренесува пулсот на музичкиот бит во не само она, што се нарекува урбан, туку и светски отворен звук: ЉУБОЈНА во Филхармонија!'},
 {'title': 'КК МЗТ Скопје Аеродром – КК Тиквеш',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/03/Untitled-Project-19.png',
  'location': 'Спортски центар „Јане Сандански”',
  'price': '100ден.',
  'time_start': '18:30',
  'date_start': '16-03-2026',
  'city': 'Скопје',
  'description': None},
 {'title': 'НАЦИОНАЛЕН ЏЕЗ ОРКЕСТАР СО MIKE HOLOBER',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/njo-mart.png',
  'location': 'Национална Oпера и Балет',
  'price': '1000ден.',
  'time_start': '20:00',
  'date_start': '18-03-2026',
  'city': 'Скопје',
  'description': 'НАЦИОНАЛЕН ЏЕЗ ОРКЕСТАР Mike Holober – диригент This Rock We’re On: Imaginary Letters 18 март | Национална опера и балет | 20:00 часот Солисти: Андријана Јаневска – вокал, Кирил Јосифов – виолончело, Влатко Нушев – вибрафон и перкусии На 18 март, Националниот џез оркестар ќе ја има ексклузивната чест да го изведе најновиот проект на Mike Holober – This Rock We’re On: Imaginary Letters, под диригентство на самиот автор. Mike Holober е еден од најзначајните современи џез композитори и аранжери, препознатлив по својата виртуозност, изразена оркестарска визија и длабока музичка чувствителност. Неговиот проект This Rock We’re On: Imaginary Letters е оценет како „монументално ремек-дело“ и „мајсторска лекција по композиција за џез оркестар“. Во ова дело, Holober создава впечатлив спој на два музички света, вметнувајќи ја суптилната естетика на современата класична музика, нагласена преку интимната камерна звучност на виолончелото, пијаното, вибрафонот и вокалот, во моќната и динамична енергија на биг бендот. Делото претставува длабока уметничка рефлексија за убавината на природата и судбината на планетата. Конципирано е како циклус од таканаречени „замислени писма“ посветени на писатели, уметници и активисти кои својот живот го поминале во восхит и грижа за планетата. Секое „писмо“ е проследено со инструментална оркестарска интерпретација што ја продлабочува и музички ја отсликува неговата содржина и поетска димензија. Овој концерт претставува ретка можност да се доживее комплексноста и длабочината на проектот на Holober во живо, под негово диригентство, во изведба на Националниот џез оркестар и специјалните гости. Ве покануваме да бидете дел од една исклучителна музичка вечер.'},
 {'title': 'Глумците Пеат 24.03',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/01/гп0326.png',
  'location': 'Македонски Народен Театар',
  'price': '1000-1800ден.',
  'time_start': '20:00',
  'date_start': '24-03-2026',
  'city': 'Скопје',
  'description': '„Глумците ПЕАТ“ е ексклузивно сценско шоу, едно од најпосакуваните и најпосетувани сценски настани кај нас. Се одржува секоја година во март, во чест на 27 март, Светскиот ден на театарот и е уникатно без реприза. И оваа година подготвуваме забавно и уникатно шоу со многу глумци и уметници. Режисер: Дејан Пројковски Диригент: Љупчо Мирковски Кореограф: Олга Панго МНТ, 24 и 25 март 2026 година Почеток 20:00 часот'},
 {'title': 'Глумците Пеат 25.03',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/01/гп0326.png',
  'location': 'Македонски Народен Театар',
  'price': '1000-1800ден.',
  'time_start': '20:00',
  'date_start': '25-03-2026',
  'city': 'Скопје',
  'description': '„Глумците ПЕАТ“ е ексклузивно сценско шоу, едно од најпосакуваните и најпосетувани сценски настани кај нас. Се одржува секоја година во март, во чест на 27 март, Светскиот ден на театарот и е уникатно без реприза. И оваа година подготвуваме забавно и уникатно шоу со многу глумци и уметници. Режисер: Дејан Пројковски Диригент: Љупчо Мирковски Кореограф: Олга Панго МНТ, 24 и 25 март 2026 година Почеток 20:00 часот'},
 {'title': '„Миланова игра“ – концерт во чест на Милан Завков',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/01/миланова-игра.png',
  'location': 'Македонска Филхармонија',
  'price': '800ден.',
  'time_start': '20:00',
  'date_start': '27-03-2026',
  'city': 'Скопје',
  'description': '„Миланова игра“ е концерт-омаж посветен на еден од највлијателните македонски композитори и културни дејци – Милан Завков, автор кој со своето дело остави длабок белег во развојот, негувањето и афирмацијата на македонската народна музика и фолклор. Овој концерт има за цел повторно да го приближи неговото творештво до публиката преку современи музички интерпретации што ги спојуваат традицијата и современиот израз, при што делата ќе бидат изведени со камерен оркестар, специјално оформен за оваа пригода. Програмата ќе опфати избрани вокални и инструментални композиции од опусот на Завков, кои ќе бидат преработени од двајца врвни аранжери – Дамир Имери и Дарко Илиевски. Нивните нови аранжмани ќе внесат свежина и модерност, комбинирајќи ја топлината на народниот звук со современи музички пристапи, хармонски решенија и оркестрации прилагодени за камерна изведба. „Миланова игра“ е можност да се слушне наследството на Милан Завков како жива, актуелна и уметнички релевантна музика, наменeта за оние што ја препознаваат вредноста на македонската фолклорна традиција и сакаат музика со културен контекст, приказна и длабочина.'},
 {'title': 'GrandVin 2026',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/03/гранд-вин.png',
  'location': 'Skopje Marriott Hotel',
  'price': '750ден.',
  'time_start': '14:00',
  'date_start': '28-03-2026',
  'city': 'Скопје',
  'description': '“ГОЛЕМА ВИНСКА ПРОЛЕТ ! GrandVin 2026 Spring Wine Salon Пронајдете го вашето ново вино, зголемете го винското искуство. Преку 300 вина, нови берби, сорти, купажи, кои ќе бидат или штотуку се лансирани на пазарот, ве чекаат за дегустација. Љубителите на посилната капка ќе можат да вкусат јаки алкохолни пијалоци од македонските дестилерии. Оваа година можност да се вкусат и наградените вина од меѓународните натпревари на штандот на Concours Mondial de Bruxelles “'},
 {'title': 'STEFANI & THE UPPER ROOM',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/01/stefani.png',
  'location': 'Младински Културен Центар',
  'price': '500-800ден.',
  'time_start': '19:00',
  'date_start': '28-03-2026',
  'city': 'Скопје',
  'description': None},
 {'title': 'Beauty Expo ’26',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/02/beauty.jpg',
  'location': '05-04-2026',
  'price': '200ден.',
  'time_start': 'Скопје',
  'date_start': '03-04-2026',
  'city': 'Хотел Александар Палас',
  'description': 'Од 03 до 05 април 2026 година, Скопје станува центар на убавината. Во градот пристигнува Beauty Expo ’26 – Саемот за козметика, настан што ги спојува професионалната експертиза и секојдневната нега на едно место – со понуди и цени што се резервирани само за саем. Ова не е саем само за експерти. Ова е саем за секоја жена што сака да купува паметно, да испроба нови производи, да најде проверени решенија за нега и убавина и да си замине со козметика по саемски цени, директно од брендот. На Beauty Expo ’26 ќе се претстават повеќе од 50 изложувачи од сите сфери на козметичката индустрија: нега на кожа и тело,професионална и домашна нега на коса,шминка и декоративна козметика,нокти и nail-индустрија,парфеми,органска и природна козметика, естетска козметика, филери и професионални третмани Посетителите ќе имаат пристап до над 200.000 различни производи од врвни светски марки, со ексклузивни попусти и понуди достапни само за време на саемот. Истовремено, козметичари, салони, студија за убавина и парфимерии ќе можат да се снабдат со производи, апарати и новитети по професионални и набавни цени, да остварат директни контакти со брендови и да ги следат најновите трендови во индустријата. На Beauty Expo ’26 ве очекуваат: вистински саемски попусти,ексклузивни понуди за крајни потрошувачи и професионалци, нови брендови и иновации,презентации, демонстрации и стручни совети,инспирација за лична нега и професионален развој Ова е местото каде што убавината се купува информирано – и по најдобра цена.'},
 {'title': 'ПОТОЧИЊА 2026',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/03/MK-Tikets-Banner-1.jpg',
  'location': '19-04-2026',
  'price': '18-04-2026',
  'time_start': 'Скопје',
  'date_start': '18-04-2026',
  'city': 'Национална Oпера и Балет',
  'description': 'Најмили другарчиња, Време е за уште една голема фестивалска забава! Поточиња 2026 на 18 и 19 април во Македонска Опера и балет ни ја носат пролетта, насмевката и радоста во Скопје на задоволство на цела Македонија. Термините на фестивалските претстави се од 11:00 ; 13:00 и 19:00 часот Дојдете заедно да направиме нови спомени од уште едно големо фестивалско шоу! Цена на билет: 500 денари *Почитувани родители, бирајте ги внимателно термините и своите билети бидејќи рефундација и/или замена на билети е возможна само во случај на откажување на настанот, во спротивно билетите важат само за терминот, редот и седиштето за кога е купен билетот*'},
 {'title': 'Cafe De Anatolia SHOW',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/03/New-Project-1.jpg',
  'location': 'Public Room (Јавна Соба)',
  'price': '700ден.',
  'time_start': '21:00',
  'date_start': '08-05-2026',
  'city': 'Скопје',
  'description': 'За прв пат во Скопје доаѓа светскиот бренд Cafe De Anatolia со CDA SHOW – лидерите на Organic House жанрот! Уживајте во магична вечер со Organic House и Afro House музика, танц перформанси и пантомима, како и ексклузивна промоција на Cafe De Anatolia вино. Вечер каде музиката, уметноста и вкусот се спојуваат во едно незаборавно искуство.'},
 {'title': 'Горан Винчиќ Винча – Комедијата е сериозна работа',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/01/vinca.jpg',
  'location': 'Македонска Филхармонија',
  'price': '1200-1800ден.',
  'time_start': '20:00',
  'date_start': '08-05-2026',
  'city': 'Скопје',
  'description': 'Еден од најпопуларните стенд-ап комичари во регионот, Горан Винчиќ – Винча, пристигнува со голема турнеја во 2026 година за своето трето самостојно шоу! По хитовите „Дежурен виновник“ и „Кажи ми дека се шегуваш“, Винча носи целосно нов материјал – поостар, поискрен и брутално смешен. Новиот проект го секцира современиот свет со хумор што зборува за лудото време во кое живееме, општествените апсурди и вистините што најчесто се туркаат под тепих. „Комедијата е сериозна работа“ премиерно пред македонската публика, на 8 мај во Филхармонија.'},
 {'title': 'Јован Јованов, Елвир Мекиќ и пријателите',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/01/640x4202.png',
  'location': 'С.Ц. Борис Трајковски',
  'price': '800-1800ден.',
  'time_start': '20:00',
  'date_start': '06-06-2026',
  'city': 'Скопје',
  'description': 'На 6 јуни 2026 година, во Арена „Борис Трајковски“ – Скопје, ќе се одржи голем концерт на Јован Јованов и Елвир Мекиќ, заедно со специјални гости. Публиката ќе има можност да ужива во најпознатите хитови, песни што обележаа едно време и создадоа незаборавни спомени. Dress code: WHITE Доколку можете ве покануваме да дојдете облечени во бело за подобро светлосно-визуелни ефекти и да бидете дел од оваа посебна вечер. Концертот е замислен како еднократен музички настан, исполнет со емоции, носталгија и врвна продукција. Инфо за високи маси: Ваучерот за високи маси вклучува 4 карти. Со купување на ваучерот, во рок од 48 часа ќе добиете линк на вашата е-маил адреса, преку кој ќе можете дополнително да докупите 1, 2 или 3 карти.'},
 {'title': 'Д фестивал 2026',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/11/mk-tickets-640x420-1.jpg',
  'location': '28-06-2026',
  'price': '2000ден.',
  'time_start': '',
  'date_start': '26-06-2026',
  'city': 'Штип',
  'description': 'Од 26 до 28 јуни во Штип ќе се одржува 16 издание на најголемиот летен open-air музички фестивал кај нас – Д ФЕСТИВАЛ! Единствениот мултимедијален настан каде што музиката, уметноста и заедништвото се спојуваат во едно уникатно доживување, оваа година се враќа во полн сјај, со сите свои карактеристични сегменти и со бројни новости во својот програмски концепт. IDLES ПРЕМИЕРНО ВО МАКЕДОНИЈА! Веќе е потврден и првиот хедлајнер за Д ФЕСТИВАЛ 2026, еден од најважните live бендови на планетата во моментов – IDLES! Милениците на македонската публика, KOIKOI ново име на Д Фестивал 2026! Еден од најатрактивните бендови на алтернативната сцена на Балканот, со незапирлива енергија, пргав ритам и поетска бруталност се придружува на Д забавата. Првите влезници се во продажба со најповолната цена во омилената РАН КОРМОРАН акција – најдоцна до 31 декември 2026.'},
 {'title': 'СФЕСТ ФЕСТИВАЛ',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2026/03/sfest.png',
  'location': '26-07-2026',
  'price': '500ден.',
  'time_start': 'Струмица',
  'date_start': '24-07-2026',
  'city': 'Градски парк Струмица',
  'description': 'Ова лето, Струмица станува фестивалски град. По успешното прво издание, СФЕСТ се враќа уште поголем, погласен и поенергичен. Од 24 до 26 јули, три дена музика, светло, звук и незаборавна атмосфера ќе ја претворат Струмица во место каде што се слави музиката и заедништвото. Второто издание на Сфест носи повеќе од 3 stages, разновидна музичка програма и настапи од домашни и регионални артисти, создавајќи вистинско фестивалско искуство кое ќе ги обедини љубителите на музиката од целиот регион. СФЕСТ не е само настан – СФЕСТ е движење. Фестивал создаден со идеја да остави траен белег и да прерасне во фестивал на градот Струмица, место каде што секое лето илјадници луѓе ќе се собираат за да ја почувствуваат енергијата на музиката. Подгответе се за 3 дена музика, енергија и моменти што ќе се паметат цела година. sfest.mk СФЕСТ 2026 Струмица | 24 – 26 Јули Први 100 влезници: ✨ 500 ДЕН. Следна цена: 🎫 600 ДЕН.'},
 {'title': 'AUTECHRE',
  'image_url': 'https://mktickets.mk/wp-content/uploads/2025/12/mktickets-banner.jpeg',
  'location': 'Младински Културен Центар',
  'price': '1500ден.',
  'time_start': '22:00',
  'date_start': '02-10-2026',
  'city': 'Скопје',

In [73]:
# # Пример со реден број за да се види колку настани има вкупно.
# events_ordering = []
#
# for idx, link in enumerate(unique_detail_events, start=1):
#     event = scrape_event_detail(link)
#     if event:
#         event['number'] = idx
#         events.append(event)
#
# events_ordering

In [74]:
folder = Path("..") / "events-output"
folder.mkdir(parents=True, exist_ok=True)

file_path = folder / "events.json"

with open(file_path, "w", encoding="utf-8") as f:
    json.dump(events, f, ensure_ascii=False, indent=2)

print(f"Saved {len(events)} events to {file_path.resolve()}")

Saved 21 events to D:\Workspace\EventsAggregator-Project\mktickets_scraper\events-output\events.json